### PR TITLE
LT-18674 Migrate .ldml to v3 and update branch to 0.13_ldml3

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* Perform LIFT imports and send/receive on 0.13_ldml3 branch.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/171)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by papeh** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs, line 16 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/171#-KxsL2dwVhSN6jksHcJh:-KxsL2dwVhSN6jksHcJi:b-xi9k57) ([raw file](https://github.com/sillsdev/flexbridge/blob/e1c6e90196890ac0e5e9f19ea2f0fa6931dc7420/src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs#L16)):*
> ```Smalltalk
> 		protected override float GetModelVersionFromBranchName(string branchName)
> 		{
> 			return float.Parse(branchName.Replace("LIFT", null).Substring(0,4), NumberFormatInfo.InvariantInfo);
> ```

it may be more robust to `.Split('_')[0]` to strip the new tail.

---

*[src/TriboroughBridge-ChorusPlugin/CommandLineProcessor.cs, line 259 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/171#-KxsLUo-Jueg5dqRymr1:-KxsLUo-Jueg5dqRymr2:b-2v3umx) ([raw file](https://github.com/sillsdev/flexbridge/blob/e1c6e90196890ac0e5e9f19ea2f0fa6931dc7420/src/TriboroughBridge-ChorusPlugin/CommandLineProcessor.cs#L259)):*
> ```Smalltalk
> 				throw new CommandLineException("-liftmodel", "is missing");
> 			// So that we can support a liftmodel parameter that looks like "0.13_ldml3"
> 			if (!commandLineArgs[liftmodel].StartsWith("0.13"))
> ```

as long as we don't get to 0.130 (we shouldn't)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/171)*

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/171#-:-KyIEwTV2sFWh2VraCt8:bnfp4nl)*

**Pull request merged**
