### PR TITLE
update net462

### PR DESCRIPTION
**Pull request by hahn-kev**
this does not include a new Chorus version, nor does this upgrade other packages.

It does enable tests to be run via `dotnet test` though I ran into some test failures there (I believe they are caused by the different test environment though). When running via Rider all the tests pass. When running msbuild test, there's no failure, but there is this warning 
```
 warning : NUnit3 (FLEx-ChorusPluginTests LfMergeBridgeTests LibFLExBridge-ChorusPluginTests LiftBridge-ChorusPluginTests RepositoryUtilityTests SIL.LCModel.Utils.Tests TriboroughBridge-ChorusPluginTests) returned with exit code 15
 ```

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/411)

### CODE REVIEW

**Comment by hahn-kev** [comment]
the appveyor build is failing, but I can't see where it's configured, there's no yaml file, where is that configured?

**Comment by jasonleenaylor** [comment]
I removed the appveyor build and thought I had disabled it. I've deleted it in appveyor now.
However, the unit test results aren't actually being reported at the moment (an oversight) that's how @rmunn managed to sneak in 15 failures.
I'll fix that in a PR shortly.

**Comment by jasonleenaylor** [comment]
Oh, and an interesting bit of trivia, the response code from NUnit3 on a successful run with failed tests is the number of tests that failed.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 13 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/411#-:-OCjpNUt1t__vUG0GMDz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)

**Pull request merged**
