### PR TITLE
Correct some linux build and packaging problems

### PR DESCRIPTION
**Pull request by jasonleenaylor**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/59)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
@marksvc @mccarthyrb Please have a look and make sure this all seems reasonable.

**Comment by marksvc** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10SBJAHsHJ8dqzHhWM)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L4)):</sup>
I haven't found this yet. Is this something you haven't pushed yet?


---

<sup>**[Makefile, line 24 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10Sp8eGYCWBjXEwI1V)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L24)):</sup>
While $@ will work here, that seems more fragile and less meaningful than specifying the filename. IMO.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by jasonleenaylor** [comment]
<sup>**[Makefile, line 24 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10Sp8eGYCWBjXEwI1V)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L24)):</sup>
Agreed. How about this? git rev-parse --short HEAD >vcs_version


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by jasonleenaylor** [comment]
<sup>**[Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10SBJAHsHJ8dqzHhWM)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L4)):</sup>
oops, I had the name of the target wrong. PreparePublishingArtifacts is the actual task name it's in build.common.proj


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by marksvc** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10SBJAHsHJ8dqzHhWM)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L4)):</sup>
Ah, okay, and this happens by some C# code. 

Since this file is now not a place one looks when updating the version number of FlexBridge, this doesn't seem to be the right place for a comment that says "Hey, when you do a release, you had better first do   cd build && xbuild /t:PrepareForRelease ." 

I suggest to remove this comment, and add to the Makefile a 'source' target that prepares the source for release. For example:

    source:
        . ./environ && cd build && xbuild /t:PrepareForRelease


What do you think about that?


---

<sup>**[Makefile, line 24 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10Sp8eGYCWBjXEwI1V)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L24)):</sup>
That sounds good.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by jasonleenaylor** [comment]
<sup>**[Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10SBJAHsHJ8dqzHhWM)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L4)):</sup>
I guess that makes sense. I view the Makefile as some linux required layer over the actual build system. So I don't expect it to be the entry point of all targets.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by marksvc** [comment]
LGTM


---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/59#-K10SBJAHsHJ8dqzHhWM)** ([raw file](https://github.com/sillsdev/flexbridge/blob/ed5f69584ad8a43a0627410d3d36b4624403c3c8/Makefile#L4)):</sup>
> I don't expect it to be the entry point of all targets.

That makes sense!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by marksvc** [comment]
I too would be happier with it being 'debuild -uc -us -S -nc'.

It would probably work with just 'debuild -S' but always produce an error in the output log :)

**Comment by mccarthyrb** [comment]
Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/59)

**Comment by jasonleenaylor** [comment]
Implemented last suggestion by @mccarthyrb, LGTM

**Pull request merged**
