### PR TITLE
Make SendReceiveActionHandler more UI independent (v2)

### PR DESCRIPTION
**Pull request by ermshiperete**
Split out a new UI independent class `SendReceiveAction` that implements common S/R functionality. The caller needs to provide a `syncFunc` parameter that does the actual S/R, e.g. by calling the appropriate Chorus functions.

Also use Autofac from nuget package instead of downloading artifact.

This change depends on a Chorus change: https://github.com/sillsdev/chorus/pull/85

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/89)

### CODE REVIEW

**Comment by regnrand** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs, line 15 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KDd7ZqXq49ovpxVP1ze:-KDd7ZqXq49ovpxVP1zf:-1498586264) ([raw file](https://github.com/sillsdev/flexbridge/blob/63d9b64ce1ca2dc44343b5c713305f15fc650de8/src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs#L15)):*
Why public? FLEx Bridge trends to making only interface methods public with classes being internal to each assembly. FB also tries to avoid subclassing, in favor of using some kind of strategy class that is then used by the main class. Can that kind of approach be used here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/89)*

**Comment by ermshiperete** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs, line 15 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KDd7ZqXq49ovpxVP1ze:-KE5duJ-s821KOEEKfwp:-1740664652) ([raw file](https://github.com/sillsdev/flexbridge/blob/63d9b64ce1ca2dc44343b5c713305f15fc650de8/src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs#L15)):*
Yes, I guess I can change it to follow that approach more closely. However, I have some naming problems - maybe you can help me come up with good names for the interfaces and classes.

Here's how I could envision it to work:
- create a new public interface `LibFLExBridgeChorusPlugin.Infrastructure.Actions.ISendReceiveAction` with one method `Execute()`.
- create an internal class `LibFLExBridgeChorusPlugin.Infrastructure.Actions.SendReceiveAction` that implements `ISendReceiveAction` and has the attribute `[Export(typeof(ISendReceiveAction))]`.

-  `FLEx_ChorusPlugin.Infrastructure.ActionHandlers.SendReceiveActionHandler` implements `IBridgeActionTypeHandler` and `IBridgeActionTypeHandlerCallEndWork`. Its `StartWorking` method gets the `ISendReceiveAction` object from the container and calls the `Execute()` method.

`SendReceiveActionHandler` implements the UI/Flex specific parts of the action (creating the Chorus system (`ChorusSystemSimple`), and displaying the sync dialog which also performs the actual sync), so `SendReceiveAction` needs to be able to call those parts.

This could be done either by passing delegates to `Execute`, or by creating another interface `ISendReceiveActionDecorator` that `SendReceiveActionHandler` implements and registers in the container. `SendReceiveAction` would then ask the container for the `ISendReceiveActionDecorator` object.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/89)*

**Comment by regnrand** [comment]
I added some comments, but it seems like there are too many changes than were done to really support a simple single Send/Receive operation by LF. I'm working up changes to the new "LfMergeBridge" class that ought to be enough to do only that basic S/R task.

---

Review status: 0 of 41 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/FLEx-ChorusPlugin/Infrastructure/FLExBridgeChorusSystem.cs, line 10 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KEsNO4734l20yrcgwgP:-KEsNO4734l20yrcgwgQ:-422922124) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/FLEx-ChorusPlugin/Infrastructure/FLExBridgeChorusSystem.cs#L10)):*
Why do we need this subclass? It doesn't add any behavior to to the base class?

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 19 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFPsCPCKxLewkPy7swj:-KFPsCPCKxLewkPy7swk:-1797355516) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LfMergeBridge/LfMergeBridge.cs#L19)):*
If this class is your entry point from LF, then LF must have its own dependencies on Chorus, in order for LF to be able to create the "ILfMergeBridgeDataProvider" implementation (it uses 'RepositoryAddress' from Chorus).

I would have expected ILfMergeBridgeDataProvider to use HttpRepositoryPath, instead, but better, to not even have LF depend on Chorus at all.

---

*[src/LfMergeBridge/Infrastructure/ActionHandlers/LfMergeSendReceiveActionHandler.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFVMABCAOlO5wM5rJOy:-KFVMABCAOlO5wM5rJOz:1248839065) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LfMergeBridge/Infrastructure/ActionHandlers/LfMergeSendReceiveActionHandler.cs#L7)):*
FB doesn't want  any dependencies on Autofac. It is only included in one of the projects now, to make sure it is in the build output folder, so Chorus can use it during some file type handler tests.

Chorus has long desired to use MEF and be rid of Autofac. But, MEF 1.0 was not developed enough to be a replacement for Autofac. MEF 2.0 may be able to do it all now, but that would require upgrading to .Net 4.5, and that would be a big switch.

---

*[src/LfMergeBridge/Infrastructure/ActionHandlers/LfMergeSendReceiveActionHandler.cs, line 35 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFRBQcHql8zsgYXmIk9:-KFRBQcHql8zsgYXmIkA:983203099) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LfMergeBridge/Infrastructure/ActionHandlers/LfMergeSendReceiveActionHandler.cs#L35)):*
Having just the 'fix it' exe file name, won't be enough. It must have the full pathname to it. Otherwise, it can't find it to run it.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 33 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFR3Zj9NKwlerCzOoz7:-KFR3Zj9NKwlerCzOoz8:-1557272276) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L33)):*
The FB preferred mechanism is to create an interface and then have two implementations of it: 1) FB code implements it using the current code, and 2) your new code implements it using its "Do Nothing" method. Then, MEF just imports the one implementation it can find in the sea of installed dlls. Then the main adjunct "CheckRepositoryBranches" delegates the work to that new, imported by MEF, interface impl.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs, line 56 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFPw2tQ1C9nkN6OLFyA:-KFPw2tR99MopTYbu8u5:-85673922) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs#L56)):*
How will LF know to cancel it, if it S/R hangs, or the user simply wants to stop it?

---

*[src/TriboroughBridge-ChorusPlugin/Utilities.cs, line 95 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KEsMjZ0SRK1MB1hf6XV:-KEsMjZ1W6s6mViZMhYh:-1512120619) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/TriboroughBridge-ChorusPlugin/Utilities.cs#L95)):*
Go ahead and get rid of it. There can't be any users of it outside of the FB repository.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-:-KFW994pP9Z6EkqwMeyt:-1382152011)*

**Comment by ermshiperete** [comment]
Superseded by #92

**Comment by ermshiperete** [comment]
Review status: 0 of 41 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/FLEx-ChorusPlugin/Infrastructure/FLExBridgeChorusSystem.cs, line 10 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KEsNO4734l20yrcgwgP:-KFdjpneDsllOJBlYoHj:-1579970021) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/FLEx-ChorusPlugin/Infrastructure/FLExBridgeChorusSystem.cs#L10)):*
I added it for MEF so that we get the IChorusSystem export which is needed elsewhere.

But it the latest version it's no longer included.

---

*[src/LfMergeBridge/Infrastructure/ActionHandlers/LfMergeSendReceiveActionHandler.cs, line 35 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFRBQcHql8zsgYXmIk9:-KGMt18_nW4PjXS1acnU:1611494577) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LfMergeBridge/Infrastructure/ActionHandlers/LfMergeSendReceiveActionHandler.cs#L35)):*
FixFwData.exe will be in the same directory as this assembly.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 33 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFR3Zj9NKwlerCzOoz7:-KGMt8HM9jHzE9IG6oUx:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L33)):*
Done.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs, line 56 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KFPw2tQ1C9nkN6OLFyA:-KGMtISk6WziRTSiTLsv:-1363905686) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveAction.cs#L56)):*
Done differently in the latest PR.

---

*[src/TriboroughBridge-ChorusPlugin/Utilities.cs, line 95 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/89#-KEsMjZ0SRK1MB1hf6XV:-KGMtM4i1ATs6HAXcDeJ:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/3c055fe237a3c9a795e757af7e1253389fb125ca/src/TriboroughBridge-ChorusPlugin/Utilities.cs#L95)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/89)*

**Pull request closed without merging**
