### PR TITLE
Use geckofx from nuget and new version 45

### PR DESCRIPTION
**Pull request by marksvc**
To help with making flexbridge work on bionic.

Previously flexbridge was using geckofx29 from a package dependency.
Flexbridge appears to use geckofx only on Linux.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/192)

### CODE REVIEW

**Comment by marksvc** [comment]
I'm not sure yet whether FB is actually compiling with the new geckofx45, or whether this will work when installed. But here's a start.

**Comment by papeh** [comment]
I had difficulty understanding part of the commit message. Only after reading the code did I understand it to say that FLExBridge's use of geckofx is limited to Linux.

If the project messages dialog can be opened from FieldWorks's Send/Receive menu on both Windows and Linux, and display messages, :LGTM:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.nuget/packages.config, line 5 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/192#-L41_4Q9_DTMfuW-gLxA:-L41_4Q9_DTMfuW-gLxB:b-jepfat) ([raw file](https://github.com/sillsdev/flexbridge/blob/d737c96a12de9447e41a89d8ade7fcf37e00ddd1/.nuget/packages.config#L5)):*
> ```XML
>   <package id="NUnit.Runners.Net4" version="2.6.4" />
>   <package id="Geckofx45.64.Linux" version="45.0.21.0" targetFramework="net45" />
>   <package id="Geckofx45.32.Linux" version="45.0.21.0" targetFramework="net45" />
> ```

I suppose it's not a problem per se that we are downloading Linux packages on Windows, as long as we don't do anything with them.

---

*[src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, line 156 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/192#-L41_lfXqcdpl7hrFzPa:-L41_lfXqcdpl7hrFzPb:b-hxl2dh) ([raw file](https://github.com/sillsdev/flexbridge/blob/d737c96a12de9447e41a89d8ade7fcf37e00ddd1/src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj#L156)):*
> ```XML
>       <HintPath>..\..\lib\common\Vulcan.Uczniowie.HelpProvider.dll</HintPath>
>     </Reference>
>     <Reference Include="Geckofx-Core, Culture=neutral">
> ```

these instances do not seem to be OS-specific

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/192#-:-L41a8QL-rRFlfqA3LqB:bhvq9dc)*

**Comment by papeh** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/192)*

**Comment by marksvc** [comment]
I updated the commit message.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/192#-:-L47kX1v5ZHekQTEFSf-:b-xqg0lc)*

**Comment by marksvc** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.nuget/packages.config, line 5 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/192#-L41_4Q9_DTMfuW-gLxA:-L4CMKZUwW_tQerRYcOL:b-jqhog0) ([raw file](https://github.com/sillsdev/flexbridge/blob/d737c96a12de9447e41a89d8ade7fcf37e00ddd1/.nuget/packages.config#L5)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

@marksvc Where do the Geckofx nuget packages get downloaded? Don't we need them for building?
</blockquote></details>

The commit message change isn't shown very well. It no longer downloads geckofx at all, and instead relies on geckofx from FieldWorks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/192)*

**Pull request merged**
