### PR TITLE
Update build dependencies for Ubuntu 16.04/xenial

### PR DESCRIPTION
**Pull request by marksvc**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/75)

### CODE REVIEW

**Comment by neilmayhew** [comment]
:+1:

**Comment by marksvc** [comment]
I tested last night and this patch allows FB to be packaged successfully in Ubuntu 16.04.

**Comment by neilmayhew** [comment]
Excellent!

**Comment by marksvc** [comment]
I don't have acceptance access so someone else who does can accept the PR when ready.

**Pull request merged**
