### PR TITLE
Add l10n gha

### PR DESCRIPTION
**Pull request by marksvc**
- Provide crowdin l10n file for a flatpak package build to download when including flexbridge in a flatpak package.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/359)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/359)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @marksvc)

___
*[.github/workflows/localizations.yml, line 64 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/359#-Mq-lKMe6rwRlLGnEbai:-Mq-lKMe6rwRlLGnEbaj:b6goy79) ([raw file](https://github.com/sillsdev/flexbridge/blob/0c38f5faf07fea752ca57ea42548f208192506ed/.github/workflows/localizations.yml#L64)):*
> ```
> echo >> "${GITHUB_ENV}" "BUILD_VERSION=${BUILD_VERSION}"
> ```
I'm not familiar with this form of echo, what does it do?

**Comment by jasonleenaylor** [comment]
___
*[.github/workflows/localizations.yml, line 64 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/359#-Mq-lKMe6rwRlLGnEbai:-Mq-makf2M5pMj_kZ5Qn:b-cbeo7r) ([raw file](https://github.com/sillsdev/flexbridge/blob/0c38f5faf07fea752ca57ea42548f208192506ed/.github/workflows/localizations.yml#L64)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> echo >> "${GITHUB_ENV}" "BUILD_VERSION=${BUILD_VERSION}"
> ```
I'm not familiar with this form of echo, what does it do?

</blockquote></details>

If you're adding something to the environment why not just use the 'env:' property like you did with the CROWDIN key

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/359)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[.github/workflows/localizations.yml, line 64 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/359#-Mq-lKMe6rwRlLGnEbai:-MqMFl_u1NOL6-DzeDrF:buryupj) ([raw file](https://github.com/sillsdev/flexbridge/blob/0c38f5faf07fea752ca57ea42548f208192506ed/.github/workflows/localizations.yml#L64)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

If you're adding something to the environment why not just use the 'env:' property like you did with the CROWDIN key
</blockquote></details>

So in a more familiar bash situation, 
```bash
echo >> outfile.txt "Hello there"
```
or the same thing,
```bash
echo "Hello there" >> outfile.txt
```
would append "Hello there" to outfile.txt. 
(Use of `>> outfile.txt` before the content may have made it look more alien. Use of that syntax lets me neatly line up the commands and keep the variable width payload on the right.)

I want to write something to the environment for all future stanzas in the file. I could probably use `env:`, but it would presumably need to be done at each `- name:` stanza. That's not a big deal in this file with just one more stanza, but it would become significant when combining pieces of GHA scripts.

IIRC I've tried different approaches to working with GITHUB_ENV, but github may be doing some sort of magic here where you need to do it _this way_. These lines let me set environment variables that will be available to later steps in the job. 
Docs for this are at https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/359)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[.github/workflows/localizations.yml, line 64 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/359#-Mq-lKMe6rwRlLGnEbai:-Mqu5Hi73oIq0W1po7Cf:blz9ros) ([raw file](https://github.com/sillsdev/flexbridge/blob/0c38f5faf07fea752ca57ea42548f208192506ed/.github/workflows/localizations.yml#L64)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So in a more familiar bash situation, 
```bash
echo >> outfile.txt "Hello there"
```
or the same thing,
```bash
echo "Hello there" >> outfile.txt
```
would append "Hello there" to outfile.txt. 
(Use of `>> outfile.txt` before the content may have made it look more alien. Use of that syntax lets me neatly line up the commands and keep the variable width payload on the right.)

I want to write something to the environment for all future stanzas in the file. I could probably use `env:`, but it would presumably need to be done at each `- name:` stanza. That's not a big deal in this file with just one more stanza, but it would become significant when combining pieces of GHA scripts.

IIRC I've tried different approaches to working with GITHUB_ENV, but github may be doing some sort of magic here where you need to do it _this way_. These lines let me set environment variables that will be available to later steps in the job. 
Docs for this are at https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable


</blockquote></details>

Ok, if it is a GH approved method who am I to object.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
