### PR TITLE
Move project splitting/unifying code in separate library

### PR DESCRIPTION
**Pull request by ermshiperete**
These changes require a change in Chorus (https://github.com/sillsdev/chorus/pull/79). They are necessary to have a library that doesn't have any UI so that it can be used in LanguageForge S/R.

[Review on Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/64)

### CODE REVIEW

**Comment by regnrand** [comment]
Reviewed 375 of 376 files at r1.
Review status: 215 of 216 files reviewed at latest revision, 8 unresolved discussions.

---

_[src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, line 201 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QQlPdQ8osWHgkhFLA:-K3QQlPdQ8osWHgkhFLB:1593378051) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj#L201)):_
Seems like the trend is to make the two gecko references not be OS-specific. With that in mind, I never really understood why FB needed the gecko stuff at all.

---

_[src/LibFLExBridge-ChorusPlugin/FLExProjectSplitter.cs, line 39 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3Qn-IvbYgVvDzE9ipv:-K3Qn-IvbYgVvDzE9ipw:-1486935153) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPlugin/FLExProjectSplitter.cs#L39)):_
Does all of this really need to be public?

---

_[src/LibFLExBridge-ChorusPlugin/FLExProjectUnifier.cs, line 38 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3Qmizu9sC6JX8jeBIy:-K3Qmizu9sC6JX8jeBIz:-1486935153) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPlugin/FLExProjectUnifier.cs#L38)):_
Does all of this really need to be public?

---

_[src/LibFLExBridge-ChorusPlugin/Handling/UnknownFileTypeHandlerStrategy.cs, line 17 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QfTg8b5XRIy4zYKoH:-K3QfTg8b5XRIy4zYKoI:-492061491) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPlugin/Handling/UnknownFileTypeHandlerStrategy.cs#L17)):_
Maybe add a comment about why this one does not use the 'typeof(IFieldWorksFileHandler) business. cf. code that imports UnknownFileTypeHandlerStrategy and all other IFieldWorksFileHandler impls.

---

_[src/LibFLExBridge-ChorusPlugin/Infrastructure/FieldWorksProjectServices.cs, line 15 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3Qe_aFOXGQejnJSEUL:-K3Qe_aFOXGQejnJSEUM:-1844688748) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPlugin/Infrastructure/FieldWorksProjectServices.cs#L15)):_
Does this need to be public?

---

_[src/LibFLExBridge-ChorusPlugin/Properties/Resources.resx, line 1 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QdUHTiBJe_us-YMEb:-K3QdUHTiBJe_us-YMEc:127469211) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPlugin/Properties/Resources.resx#L1)):_
Aren't many/most of these strings shown via the UI, which this lib version doesn't allow?

---

_[src/LibFLExBridge-ChorusPluginTests/FieldWorksTestServices.cs, line 20 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3Qc8Ci9wi4HnY7RVup:-K3Qc8Ci9wi4HnY7RVuq:-1699657842) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPluginTests/FieldWorksTestServices.cs#L20)):_
Does all of this need to be public? If the regular FB tests need to access this, it can be granted access to internals, no?

---

_[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QVKwy4rxo65QZoMva:-K3QVKwy4rxo65QZoMvb:-919599957) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs#L11)):_
Can you add a class comment and comments to all public stuff? The FB system has never been picky about this, but they are nice to have.

BTW, nice job of refactoring this chunk of code. Thx.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/64)_

**Comment by regnrand** [comment]
I added some comments/questions, but the basic direction the changes are headed are fine.

---

Reviewed 1 of 376 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-:-K3R4CuT_csymj_8E-js:-1256410794)_

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, line 201 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QQlPdQ8osWHgkhFLA:-K3VSRjUMsk-cn5SeFk0:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj#L201)):_
Done.

---

_[src/LibFLExBridge-ChorusPlugin/Properties/Resources.resx, line 1 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QdUHTiBJe_us-YMEb:-K3VZkMQSKFu24uNGkJ3:2006809405) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibFLExBridge-ChorusPlugin/Properties/Resources.resx#L1)):_
A lot of the strings might be used in the UI, yes. But there are quite a number of strings that are used in exception messages etc, so it seemed easier to put the entire Resources.resx file in this library.

---

_[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3QVKwy4rxo65QZoMva:-K3Vf4zcFqFvN8E-3nI3:421436109) ([raw file](https://github.com/sillsdev/flexbridge/blob/a19113f8673b698783b6de3a3bb3dbe61fa1f441/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs#L11)):_
Done. Could you check the comment if it describes what the methods really do?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/64)_

**Comment by regnrand** [comment]
Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/LibFLExBridge-ChorusPlugin/FLEx.cs, line 1 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3VlIRQGltOUuD5f_E-:-K3VlIRQGltOUuD5f_E0:1327006558) ([raw file](https://github.com/sillsdev/flexbridge/blob/c6d5d5e54301a01e3c70d8f704d202c4c7b48266/src/LibFLExBridge-ChorusPlugin/FLEx.cs#L1)):_
I never did set up a full set of tests for round trip splitting/joining, because I wrote that FwDataNester app to do that on real data sets. That test app would split up all selected projects (I used ~40 of them), and then rebuild the fwdata file. The test app would then compare the original fwdata file with the rebuilt one and report any differences. I had to have a good explanation for there being any differences at all. ;-) Granted, it was easier to manage all of that hand testing, back when I was the only one working on FB code.

---

_[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs, line 104 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/64#-K3Volc8RjIClIWzg22f:-K3Volc8RjIClIWzg22g:1105781326) ([raw file](https://github.com/sillsdev/flexbridge/blob/c6d5d5e54301a01e3c70d8f704d202c4c7b48266/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs#L104)):_
Go ahead and do it, if you want to.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/64)_

**Pull request merged**
