### PR TITLE
Fix Chorus.Mercurial package issue on Linux

### PR DESCRIPTION
**Pull request by rmunn**
Version 6.5.1.25 of the SIL.Chorus.Mercurial package had a few missing files that cause test failures in some circumstances; 6.5.1.29 fixes that omission.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/399)

### CODE REVIEW

**Comment by rmunn** [comment]
I should note that the missing files are compiled C extensions, which I compiled for Python 3.8 and above since those are the currently-supported versions of Python (3.7 went out of support in October 2023, earlier versions were of course earlier than that). But our TeamCity build agent for linux64, which has been failing to build ever since the SIL.Chorus.Mercurial package was updated to 6.5.1 (which requires Python 3), is running Ubuntu Xenial, where the Python version was 3.5.

If we want to get this building on TeamCity, we might need to update the build runner over there to Ubuntu 22.04. (Or even 24.04, which just came out today). Either that, or move the NuGet packaging-and-release build to GitHub Actions.

(I don't care where it builds, I just want it to be able to consume a NuGet package with the changes from https://github.com/sillsdev/flexbridge/pull/398).

**Comment by rmunn** [comment]
PR 397 [changes the package version to `6.*`](https://github.com/sillsdev/flexbridge/pull/397/files#diff-d071cf6f93578667b04cab0f957540f914291c0a7f6f0795bcb960948bb3dd96R15) so that it will automatically pull in any future Mercurial packaging fixes. I'll change this PR to do the same so that PR 397 won't have any merge conflicts to deal with once it's ready to merge.

**Comment by rmunn** [comment]
@jasonleenaylor - Any objections to my merging this before PR #397 is fully ironed out? I've been holding off so as to not cause merge conflicts, but perhaps that's a little silly for a one-line change.

**Comment by jasonleenaylor** [comment]
Robin, sorry I didn't see your comment here earlier. After merging this with the results of the ci-cd build there are no changes left in this commit, so I'm going to close the PR.

**Pull request closed without merging**
