### PR TITLE
Add update-version script

### PR DESCRIPTION
**Pull request by marksvc**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/62)

### CODE REVIEW

**Comment by papeh** [comment]
should we validate CHANNEL (Alpha, Beta, Stable)


---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/62)

**Comment by jasonleenaylor** [comment]
We could also use this script to grab the proper user information and change PreparePublishingArtifacts to optionally take that information instead of always claiming that I did it.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/62)

**Comment by marksvc** [comment]
Validate CHANNEL - Sure. Done. I used Alpha, Beta, and Stable, which are hopefully the correct set of channels to allow.

Jason: Good idea. I suppose we could get that information from the user's git author name and git author email. Though I would be in favor of not even putting a name in the changelog but just writing something like "FlexBridge Team <>" for the author  and email address. Do you have an opinion about that?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/62#-:-K8PyrRMIti1iV_cTl1s:848945271)*

**Comment by papeh** [comment]
:+1: 
You may wish to update the ReadMe to recommend using this script.

**Comment by papeh** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/62)*

**Pull request merged**
