### PR TITLE
Add new 'uniform interface' method to LF Bridge

### PR DESCRIPTION
**Pull request by regnrand**
1. Adds three new action handlers for LF Brideg to handle:
   A. New clone
   B. Update to given long hash (long SHA)
   C. Normal Send/Receive
2. Old S/R method is present, but marked obsolete.
3. Fixed up some tests that appeared to work, but did not.
4. Add new LF Bridge test app that can be used for manual testing
   of the action handlers.
5. Moved some stuff from original assembly to UI-free assemblies.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/95)

### CODE REVIEW

**Comment by ermshiperete** [comment]
Thanks for your work! I added some comments. I didn't carefully look at the long sha code yet.

Also, IMO it would be good if the Chorus parts would be moved to Chorus before submitting this PR and proper tests for those parts added.

---

Reviewed 61 of 61 files at r1.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[src/FLExBridge/Program.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvrUXt06C_40W-Ouk7:-KGvrUXt06C_40W-Ouk8:1041247580) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/FLExBridge/Program.cs#L31)):*
_neext_? I guess that should be _need_?

---

*[src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs, line 21 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvvGbkMSS8scZpk09v:-KGvvGbkMSS8scZpk09w:-791065497) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs#L21)):*
What do you consider an empty source repo? If there are no commits, or where `.hg` doesn't exist?

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 37 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvudcaKBzkMBd9AZGc:-KGvudcbHnhrXBUFQe51:-1912808347) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L37)):*
s/than/then/

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 67 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvwvpuknubdZ2M2T1B:-KGvwvpuknubdZ2M2T1C:764183470) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L67)):*
yes, that's fine, at least for now.

---

*[src/LfMergeBridge/LanguageForgeUpdateToLongHashActionHandler.cs, line 39 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvyv-7vUzJFS6GcnZ5:-KGvyv-7vUzJFS6GcnZ6:1367822785) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeUpdateToLongHashActionHandler.cs#L39)):*
If we want to get rid of the use of Chorus in LfMerge then I think we have to tell LfMerge more explicitly that an error happened. LfMerge won't notice it if if the error is only reported through `progress`. We should either throw an exception or return an error value.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 28 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvzvFSSfPmqPpyt9uM:-KGvzvFTMVrTchW2d4P9:1809570476) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L28)):*
s/happeend/happend/

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 29 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw--InqjZEXR1d1APP:-KGw--InqjZEXR1d1APQ:-2082323255) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L29)):*
s/specified completed/specified action completed/

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw-5tVru5yPartjpJu:-KGw-5tVru5yPartjpJv:-820649540) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L31)):*
s/meenas/means/

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 41 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw9Kt7RomC_jXM3_Bf:-KGw9Kt7RomC_jXM3_Bg:651228371) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L41)):*
That is not true. It would be better to set `somethingForClient` to the error string (maybe in addition to `progress.WriteError()`.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 76 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw0VesO6--WPbmrcfp:-KGw-zUVkN4H1P1jJy2v:-1209571332) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L76)):*
I'm not sure catching all exceptions here is the best way. I'd prefer letting LfMerge catch them. 

---

*[src/LfMergeBridge/LfMergeBridgeUtilities.cs, line 25 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw1K2CYEzy_OXU0Q5d:-KGw1K2CYEzy_OXU0Q5e:48516239) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridgeUtilities.cs#L25)):*
s/give/given/

---

*[src/LfMergeBridge/LfMergeBridgeUtilities.cs, line 71 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw1jzRm2GhDHkCl-5N:-KGw1jzSVRtk6sXMMSD6:1949366200) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridgeUtilities.cs#L71)):*
I don't think this should be passed through `progress`. Progress is used for status messages and intended to be read by the developer, not by the application.

---

*[src/LfMergeBridgeTestApp/LfMergeBridgeTestApp.csproj, line 37 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw2l1jfQ5L3B2UMmkf:-KGw2l1jfQ5L3B2UMmkg:1613500728) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridgeTestApp/LfMergeBridgeTestApp.csproj#L37)):*
This file should have `DebugMono` and `ReleaseMono` configurations and configuration specific references to `Palaso.dll`. Currently the build fails on Linux because it can't find Palaso (https://jenkins.lsdev.sil.org:45192/view/LfMerge/view/All/job/GitHub-FlexBridge-Linux-any-lfmerge-release/33/).

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw50YOEV8IDLMK-5UB:-KGw50YOEV8IDLMK-5UC:-1746855382) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L108)):*
No, they are not a problem.  Mono implements things differently on Linux, so it doesn't show a window regardless of the properties.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 120 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw5I34B5qNAw-7siDi:-KGw5I34B5qNAw-7siDj:756486854) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L120)):*
yep, it already returns these exit codes.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs, line 10 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw5zEFMOZOqkcX64ur:-KGw5zEFMOZOqkcX64us:2133185715) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs#L10)):*
Talking about "-v" command line option no longer makes sense after moving the file here and having LfMergeBridge actions.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs, line 18 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw5pzUJ0VMtTFaHSv_:-KGw5pzUJ0VMtTFaHSva:1643302413) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs#L18)):*
Should this be `public` or can it be `internal`?

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs, line 9 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6Jtt3VeigYByI78E:-KGw6JtuBgt8AxPVo44f:562083566) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs#L9)):*
s/oif/if/

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6EGWxxq5_KIaFzYw:-KGw6EGWxxq5_KIaFzYx:568583907) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs#L11)):*
`public` or `internal`?

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs, line 13 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6SGoCxIm1cJSZxOh:-KGw6SGoCxIm1cJSZxOi:872889156) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs#L13)):*
s/./,/ ?

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/StringToActionTypeConverter.cs, line 9 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6eQEVqZ32W9RVh2s:-KGw6eQFLNIzCd5DuZZO:979237843) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/StringToActionTypeConverter.cs#L9)):*
s/srtring/string/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-:-KGwAQTAvPn1fHF_tZRJ:-2121294902)*

**Comment by regnrand** [comment]
I had thought of adding the code first to Chorus, but opted to not do that, in favor of doing this first here. 

1. Doing it the other way, would have first required the changes to be made in Chorus, and then only after they had been accepted could this repo have been changed in the easiest way.
2. There is a long history of FB development where things were first done in FB and then moved into Chorus.
3. Making the changes first in FB allows for both Chorus and LFMerge to be updated  afterwards and with no breaking changes (none were expected for either).

---

Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[src/FLExBridge/Program.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvrUXt06C_40W-Ouk7:-KGxXxWbAppiUxdFAunS:129217772) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/FLExBridge/Program.cs#L31)):*
'expect'

---

*[src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs, line 21 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvvGbkMSS8scZpk09v:-KGxY8Lhrz8ZwRQUn7il:1330216984) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs#L21)):*
If the Language Depot repo exists (.hg folder and its basic contents exist), but it has no commit 0, then it is 'empty'. That can be cloned, but the first user to do a push that has a commit 0, then sets the stage for all other clones of the same project, since it provides all clones with the commonly shared commit 0 identifier (aka SHA), which tells Mercurial the repos are the 'same'. Mercurial does support merging two unrelated repos (not the same commit 0 id), but it requires a special command line switch to make it happen. (Chorus won't support using that switch.)

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 37 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvudcaKBzkMBd9AZGc:-KGxdPoE3hWZP0asXCF0:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L37)):*
Done.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 67 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvwvpuknubdZ2M2T1B:-KGxdZFioujq4Y74tNm-:-2096992211) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L67)):*
Ok. I removed the review note.

---

*[src/LfMergeBridge/LanguageForgeUpdateToLongHashActionHandler.cs, line 39 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvyv-7vUzJFS6GcnZ5:-KGxe0_zxg6ema7zx-rg:-1690016638) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LanguageForgeUpdateToLongHashActionHandler.cs#L39)):*
I think the called method "LfMergeBridgeUtilities.UpdateToLongHash" should be moved into the only calling method in LanguageForgeUpdateToLongHashActionHandler.  That will let the handler know more that the present 'true/false return value. The actual work of updating would still go into Chorus.

I suspected that we would need something more for LF Bridge/LfMerge interaction than that progress. We can use exceptions, but I hear those are expensive to use for program flow control mechanisms.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 28 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGvzvFSSfPmqPpyt9uM:-KGxkHY1kLWwuGKIGxbp:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L28)):*
Done.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 29 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw--InqjZEXR1d1APP:-KGxkUVBvd9V0EdRixOV:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L29)):*
Done.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw-5tVru5yPartjpJu:-KGxkgjiADFYmaQhgLn1:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L31)):*
Done.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 41 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw9Kt7RomC_jXM3_Bf:-KGxks4jUB0EnEWylOMa:-1688166222) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L41)):*
Good. I'll add it to 'somethingForClient' and put it in the progress widget, unless you prefer it it to not be in 'progress'.

Changed 'somethingForClient' comment to : // Start optimistically.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 76 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw0VesO6--WPbmrcfp:-KGxln-hD3TCRQnoT-dz:1600054858) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridge.cs#L76)):*
Got rid of try/catch to let LfMerge do the exception handling.

---

*[src/LfMergeBridge/LfMergeBridgeUtilities.cs, line 25 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw1K2CYEzy_OXU0Q5d:-KGxnVmRfXw5cybSL_QX:-1830877018) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridgeUtilities.cs#L25)):*
Done. I also marked method to go away, when Chorus supports getting the long hash.

---

*[src/LfMergeBridge/LfMergeBridgeUtilities.cs, line 71 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw1jzRm2GhDHkCl-5N:-KGxngytPjHuGyb5rt8t:-1696536801) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridge/LfMergeBridgeUtilities.cs#L71)):*
I was wondering about the best way to get this back to LfMerge, given that 'progress' will have so much other stuff in it.

One option is to add either a string return value to the main action handler "StartWorking" interface method, or to add a new 'out' parameter to the interface, like that 'out string somethingForClient' parameter on the main Execute method.

I think I like the 'out' option a bit better, since that could be passed from Execute down into StartWorking. I'll do that in the next PR, to see how that feels.

---

*[src/LfMergeBridgeTestApp/LfMergeBridgeTestApp.csproj, line 37 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw2l1jfQ5L3B2UMmkf:-KGxq38baShyNzyopx85:965255632) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LfMergeBridgeTestApp/LfMergeBridgeTestApp.csproj#L37)):*
I'll add it in the next PR.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw50YOEV8IDLMK-5UB:-KGxqIMGiGPu12N8L8do:-1575766907) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L108)):*
Good. I removed the "review me" comment.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 120 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw5I34B5qNAw-7siDi:-KGxqNax97uXrD0slStT:-1575766907) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L120)):*
Good. I removed the "review me" comment.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs, line 10 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw5zEFMOZOqkcX64ur:-KGxsTEJqG3QOLPtoKhK:438237604) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs#L10)):*
Made the comments more general and not mention the '-v' command line option.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs, line 18 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw5pzUJ0VMtTFaHSv_:-KGxqls7dI8EtPjA8v_o:-1790441070) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs#L18)):*
internal, of course. ;-)

But, I was waiting on making all those public things internal, until after LfMerge had started to use the new uniform interface method and had been freed of all dependencies on bridge code (except the uniform interface method), so as to not break anything upstream. (This was even if LfMerge never used the interface or changed it.)

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs, line 9 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6Jtt3VeigYByI78E:-KGxsvTFL6qBfTWfppgT:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs#L9)):*
Done.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6EGWxxq5_KIaFzYw:-KGxsdjGy_JMjCcJ5prs:1129814044) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandlerCallEndWork.cs#L11)):*
Also internal, but in my 'do after Lfmerge uses the uniform interface' list.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs, line 13 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6SGoCxIm1cJSZxOh:-KGxv0aAQB3qu96mX2cQ:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs#L13)):*
Done.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/StringToActionTypeConverter.cs, line 9 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KGw6eQEVqZ32W9RVh2s:-KGxvChMSTiNXcY0vzjG:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6050ee64d6a1aabbcfa6a923ae190e7f63ab9519/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/StringToActionTypeConverter.cs#L9)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-:-KGxVDBNRlvhVCOCs2XV:-1395089126)*

**Comment by ermshiperete** [comment]
I asked @megahirt to take a look at `LfMergeBridgeUtilities.cs`.

Sorry for being picky about typos - feel free to ignore those comments if they annoy you.

<details><summary><i>Previously, regnrand (Randy Regnier) wrote…</i></summary>
> I had thought of adding the code first to Chorus, but opted to not do that, in favor of doing this first here. 
> 
> 1. Doing it the other way, would have first required the changes to be made in Chorus, and then only after they had been accepted could this repo have been changed in the easiest way.
> 2. There is a long history of FB development where things were first done in FB and then moved into Chorus.
> 3. Making the changes first in FB allows for both Chorus and LFMerge to be updated  afterwards and with no breaking changes (none were expected for either).</details>


---

Reviewed 30 of 31 files at r2.
Review status: 62 of 63 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 88 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KHLENTjPx7Jnn9tnnut:-KHLENTkle1rtDal2u1q:-265766665) ([raw file](https://github.com/sillsdev/flexbridge/blob/08796c5448d78c67487c662379014f45595ba5a6/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L88)):*
> ```Smalltalk
> 			if (!syncResults.Succeeded)
> 			{
> 				// REVIEW (EberhardB(RandyR): Do you want this here, in 'somethingForClient', or in both?
> ```

in both

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 92 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KHLEQiQVFWwhiePqazG:-KHLEQiQVFWwhiePqazH:835857171) ([raw file](https://github.com/sillsdev/flexbridge/blob/08796c5448d78c67487c662379014f45595ba5a6/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L92)):*
> ```Smalltalk
> 				return;
> 			}
> 			// REVIEW (EberhardB(RandyR): Do you want this here, in 'somethingForClient', or in both?
> ```

Since this is an informational message putting it just in progress is fine I think.

---

*[src/LfMergeBridge/LfMergeBridgeUtilities.cs, line 124 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KHLGfgw1bV8ODwKtO9e:-KHLGfgw1bV8ODwKtO9f:-968749395) ([raw file](https://github.com/sillsdev/flexbridge/blob/08796c5448d78c67487c662379014f45595ba5a6/src/LfMergeBridge/LfMergeBridgeUtilities.cs#L124)):*
> ```Smalltalk
> 				var desiredParentBranchAsInt = int.Parse(desiredBranchName) - 1;
> 				foreach (var head in allHeads.Where(head => !string.IsNullOrEmpty(head.Branch) // Skip default branch's head
> 					&& int.Parse(head.Branch) <= desiredParentBranchAsInt)) // Has to be a lower model version number, since the current one is not present in repo.
> ```

I think this might be easier to read if you'd check for `int.Parse(head.Branch) < desiredParentBranchAsInt` (instead of `<=`) and initialize `desiredParentBranchAsInt` with `int.Parse(desiredBranchName)`.

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs, line 11 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KHLIeunWv7ncRQiWyR_:-KHLIeunWv7ncRQiWyRa:2112587355) ([raw file](https://github.com/sillsdev/flexbridge/blob/08796c5448d78c67487c662379014f45595ba5a6/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IBridgeActionTypeHandler.cs#L11)):*
> ```Smalltalk
> 	/// <summary>
> 	/// The interface definition that each handler must implement for one action type option
> 	/// (specified elsewhere by the client, but which matches the retrun value of the "SupportedActionType" method.
> ```

s/retrun/return/

---

*[src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs, line 17 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-KHLJA0awYug7JKVKiZX:-KHLJA0awYug7JKVKiZY:-95555509) ([raw file](https://github.com/sillsdev/flexbridge/blob/08796c5448d78c67487c662379014f45595ba5a6/src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs#L17)):*
> ```Smalltalk
> 	///
> 	/// Depending on the command line option for "-v" (Flex Bridge) or parameter 'actionType' (LfMergeBridge),
> 	/// the startup code for each major brdige entry point selects a matching handler to process
> ```

s/brdige/bridge/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/95#-:-KHLLQmWjiOA4exKkhcu:352136318)*

**Comment by megahirt** [comment]
Reviewed 33 of 61 files at r1, 26 of 31 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/95)*

**Comment by megahirt** [comment]
Randy,

Thanks for your hard work in putting all this together.  I will defer to your preference to start with code in LFMergeBridge and then move selected functions out to Chorus once it has been tested/shown to work.

I marked your PR as reviewed.  The way that LFMerge will consume the LFMergeBridge UpdateToLongSha action is something we'll work on more once we get to that point.  I appreciate that you just got something coded so we have a starting point.  I would say that if a the system was unable to update to the requested long SHA, that it should throw an exception.

**Comment by megahirt** [comment]
Unless you'd like more discussion on this Randy, I will check with Eberhard this afternoon and merge this PR.

**Comment by ermshiperete** [comment]
Reviewed 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/95)*

**Pull request merged**
