### PR TITLE
Merge feature/nuget into develop

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/316)

### CODE REVIEW

**Comment by ermshiperete** [comment]
Seems we have one test, MergeIntegrationTests.DictConfigMerge_DifferentUpradePathKeepsFileFormat, that most of the time (but not always) fails...

**Review by papeh — CHANGES_REQUESTED** [review]
> Reviewed 17 of 130 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/316)* status: 17 of 130 files reviewed, 3 unresolved discussions (waiting on @ermshiperete)

___
*[flexbridge, line 39 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZmpJH6DKvwnqFVln4l:-MZmpJH6DKvwnqFVln4m:bgmoefc) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/flexbridge#L39)):*
> `--debug`

Are we sure we want to do this on user machines, too?
___
*[Makefile, line 6 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZmqIXzBBIRrOoJ1k23:-MZmqIXzBBIRrOoJ1k24:b-3zwwc) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/Makefile#L6)):*
> ```Makefile
> CPUARCH=$(shell /usr/bin/arch)
> BUILD_NUMBER=$(BuildVersion)
> ifneq ($(origin BUILD_NUMBER), '')
> ```

Did you mean `ifeq`?
___
*[ReadMe.md, line 49 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZmtMdbAzZgkDX-CsMX:-MZmtMdbAzZgkDX-CsMY:b-h8w6j2) ([raw file](https://github.com/sillsdev/flexbridge/blob/2e3ba01966230170e4bbb997b605311c1c76e76f/ReadMe.md#L49)):*
> ```Markdown
> 
> Also, if you are working on Chorus, set up the FieldWorks build to copy locally-built Chorus and Palaso artifacts
> (instructions are located in the [FwDocumentation wiki](https://github.com/sillsdev/FwDocumentation/wiki)).
> ```

We should link to instructions for the new way to work with locally-built Chorus and Palaso artifacts

**Review by papeh — APPROVED** [review]
:lgtm:

> Reviewed 113 of 130 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/316#-:-MZnYMjF-uQexSwkl91z:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @ermshiperete)

___
*[build/TestInstallerBuild.bat, line 1 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZnTLLz3n0yy9KbVYuW:-MZnTLLz3n0yy9KbVYuX:b-1r0vbi) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/build/TestInstallerBuild.bat#L1)):*
> ```Batchfile
> REM This script assumes you have already downloaded TeamCity dependencies
> ```

no longer needed
___
*[src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs, line 185 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZnV12h8sZeIs9nesvb:-MZnV12h8sZeIs9nesvc:bb70zqp) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs#L185)):*
> ```Smalltalk
> 					var aStrEzpi = aStrElements.FirstOrDefault(el => el.Attribute("ws").Value == "qaa-x-ezpi");
> 					Assert.IsNotNull(aStrEzpi);
> 					Assert.That(aStrEzpi.Element("Run").Value, Is.EqualTo("saglo, yzaglo, rzaglo, wzaglo, nzaglo, -"));
> ```

viel besser
___
*[src/LibFLExBridge-ChorusPlugin/Handling/FieldWorksCommonFileHandler.cs, line 121 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZnWHUJ8p3jcieTN-1P:-MZnWHUJ8p3jcieTN-1Q:b-6oiwnn) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/src/LibFLExBridge-ChorusPlugin/Handling/FieldWorksCommonFileHandler.cs#L121)):*
> ```Smalltalk
> 					var parent = Directory.GetParent(folder);
> 					folder = parent?.ToString();
> 					if (folder == null)
> ```

nit: this check is now redundant

**Review by ermshiperete — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/316)* status: all files reviewed, 5 unresolved discussions (waiting on @papeh)

___
*[flexbridge, line 39 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZmpJH6DKvwnqFVln4l:-MZrtDpO01FT5DwszpoJ:b-3ymryc) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/flexbridge#L39)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

> `--debug`

Are we sure we want to do this on user machines, too?
</blockquote></details>

It doesn't hurt but gives better callstacks (i.e. with line numbers) in case of a crash.
___
*[Makefile, line 6 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZmqIXzBBIRrOoJ1k23:-MZrydSXBrwTy0SelYEQ:b-eb8fuy) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/Makefile#L6)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Did you mean `ifeq`?
</blockquote></details>

That code doesn't make much sense. Thanks!

Done.
___
*[ReadMe.md, line 49 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZmtMdbAzZgkDX-CsMX:-MZs-FbWEOAfl_HoGVNz:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/2e3ba01966230170e4bbb997b605311c1c76e76f/ReadMe.md#L49)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

We should link to instructions for the new way to work with locally-built Chorus and Palaso artifacts
</blockquote></details>

Done.
___
*[build/TestInstallerBuild.bat, line 1 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZnTLLz3n0yy9KbVYuW:-MZs04JlEpsMv6D7VNYS:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/build/TestInstallerBuild.bat#L1)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

no longer needed
</blockquote></details>

Done.
___
*[src/LibFLExBridge-ChorusPlugin/Handling/FieldWorksCommonFileHandler.cs, line 121 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/316#-MZnWHUJ8p3jcieTN-1P:-MZs-nqm0jfFg1U88gXB:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/733408fe158edeb487f6b71995c13e5ab4aae547/src/LibFLExBridge-ChorusPlugin/Handling/FieldWorksCommonFileHandler.cs#L121)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

nit: this check is now redundant
</blockquote></details>

Done.

**Review by papeh — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/316#-:-M_1uH5t1K8FodkmsP2C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

**Pull request merged**
