### PR TITLE
Download GeckoFX 45 from NuGet on Linux platforms

### PR DESCRIPTION
**Pull request by RaymondLuong3**
(cherry picked from commit 11bb91a05e313d8cd631df1471d2555f6f68eed6)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/212)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by ermshiperete** [comment]
I have one question, otherwise :lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/nuget-windows/packages.config, line 3 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/212#-L7TYxNZwbmHpbU5L4XT:-L7TYxNZwbmHpbU5L4XU:bxsfndd) ([raw file](https://github.com/sillsdev/flexbridge/blob/65fca6ee1f23614f4c2fa9c807f917e45f1c84a1/build/nuget-windows/packages.config#L3)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <packages>
> </packages>
> ```

So we don't need geckofx on Windows?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/212#-:-L7TZ16SCEMhQ_lY5CuU:b-c3so14)*

**Comment by RaymondLuong3** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/nuget-windows/packages.config, line 3 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/212#-L7TYxNZwbmHpbU5L4XT:-L7UuDRxM5JnIsvoOwPQ:bbclyde) ([raw file](https://github.com/sillsdev/flexbridge/blob/65fca6ee1f23614f4c2fa9c807f917e45f1c84a1/build/nuget-windows/packages.config#L3)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

So we don't need geckofx on Windows?
</blockquote></details>

Geckofx is not used on windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/212)*

**Pull request merged**
