### PR TITLE
Refactor FlexObtainProjectStrategyTests

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/94)

### CODE REVIEW

**Comment by regnrand** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs, line 30 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/94#-KGTMjcbMrVOS8SS8CLK:-KGTMjccpc6kfv_fpPRu:-1685894769) ([raw file](https://github.com/sillsdev/flexbridge/blob/8ee38838d7664e4ca2c1e77f41949b72d8f392cd/src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs#L30)):*
Why does it need to be the real xml? There is no need in these tests for it to be what is normally in that file, which is why I put in the bogus data. And, even if the real xml had been needed, it would have been <AdditionalFields />, just to save on bytes in the repo. ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/94)*

**Comment by megahirt** [comment]
*[src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs, line 30 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/94#-KGTMjcbMrVOS8SS8CLK:-KGV6JEHZndNJiakg-3r:-792076387) ([raw file](https://github.com/sillsdev/flexbridge/blob/8ee38838d7664e4ca2c1e77f41949b72d8f392cd/src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs#L30)):*
Using real XML helps the reader understand what that parameter is.  I don't see a problem with it, even if it adds a negligible amount of bytes to the repo :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/94)*

**Comment by regnrand** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs, line 30 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/94#-KGTMjcbMrVOS8SS8CLK:-KGV8EJV4kl0y6Nx10KK:-1198630007) ([raw file](https://github.com/sillsdev/flexbridge/blob/8ee38838d7664e4ca2c1e77f41949b72d8f392cd/src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs#L30)):*
Change it from "contents" to "bogusContents", then. By using real xml data, it suggests to a dev that it is important to use real data, where in this case, it is not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/94)*

**Comment by ermshiperete** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs, line 30 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/94#-KGTMjcbMrVOS8SS8CLK:-KGW5oa0211R2XAGAJN-:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/8ee38838d7664e4ca2c1e77f41949b72d8f392cd/src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs#L30)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/94)*

**Comment by megahirt** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/94)*

**Comment by megahirt** [comment]
Randy, per our conversation earlier today I will merge this PR as Eberhard has complied with your suggestions.  Thanks.

**Pull request merged**
