### PR TITLE
Enable support for DM69 model

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Upgrade MetaDataCache to version 69 with tests
* Add some improved exception messages to help future
  maintainers

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/103)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
@ermshiperete, @megahirt  You might want to look at this as a heads up for the model changes that will be coming with 8.3. This isn't necessarily the final cut, but we are far enough along that it might be.

**Comment by papeh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs, line 337 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/103#-KPrqYU-5Vk51ebyBZMO:-KPrqYU0S6-KjWiNrPhw:bxhgdgu) ([raw file](https://github.com/sillsdev/flexbridge/blob/59f12b7379ee6d6d16efc1b6d6a2f28ab89c0ea1/src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs#L337)):*
> ```Smalltalk
> 						newClass.RemoveProperty("Etymology");
> 						newClass.AddProperty(new FdoPropertyInfo("Etymology", DataType.OwningSequence));
> 						// Change Restrictions from MultiString to MultiUnicode in LexSense
> ```

misplaced comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/103)*

**Comment by papeh** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/103)*

**Comment by papeh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs, line 337 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/103#-KPrqYU-5Vk51ebyBZMO:-KPrxxueiymF6ERkplWU:b-38kk51) ([raw file](https://github.com/sillsdev/flexbridge/blob/59f12b7379ee6d6d16efc1b6d6a2f28ab89c0ea1/src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs#L337)):*
<details><summary><i>Previously, papeh wrote…</i></summary>
> misplaced comment
</details>
Also, `Restrictions` seems to be changing *to* MustiString.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/103)*

**Comment by jasonleenaylor** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs, line 337 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/103#-KPrqYU-5Vk51ebyBZMO:-KPsiI2lj6lScGOLmC1Y:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/59f12b7379ee6d6d16efc1b6d6a2f28ab89c0ea1/src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs#L337)):*
<details><summary><i>Previously, papeh wrote…</i></summary>
> Also, `Restrictions` seems to be changing *to* MustiString.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/103)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/103#-:-KQ6JY1_Y6LbtJkajBed:bnfp4nl)*

**Pull request merged**
