### PR TITLE
Update dependencies and reference to SIL.Reporting

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/214)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by marksvc** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[download_dependencies_linux.sh, line 208 at r1](https://beta.reviewable.io/reviews/sillsdev/flexbridge/214#-L7kflW0-CtiubOTJGvW:-L7kflW0-CtiubOTJGvX:br8tvqc) ([raw file](https://github.com/sillsdev/flexbridge/blob/54fc207e1f024da41ae5a52d9ebe90215ebe5d4c/download_dependencies_linux.sh#L208)):*
> ```Shell
> copy_auto http://build.palaso.org/guestAuth/repository/download/PalasoTrusty64masterContinuous/latest.lastSuccessful/NDesk.DBus.dll.config ./lib/ReleaseMono/NDesk.DBus.dll.config
> copy_auto http://build.palaso.org/guestAuth/repository/download/PalasoTrusty64masterContinuous/latest.lastSuccessful/debug/SIL.Core.dll ./lib/DebugMono/SIL.Core.dll
> copy_auto http://build.palaso.org/guestAuth/repository/download/PalasoTrusty64masterContinuous/latest.lastSuccessful/debug/SIL.Core.dll.config ./lib/DebugMono/SIL.Core.dll.config
> ```

That concerns me that the .dll.config disappeared from the list, but this .sh file is generated, so hopefully that means we don't need the .dll.config any more.

I see some .mdb files are gone now, too. 

Maybe both have to do with using .NET Standard or Mono 5 or something.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/flexbridge/214#-:-L7kgDII0KwTsYaOw6zX:bnfp4nl)*

**Comment by RaymondLuong3** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[download_dependencies_linux.sh, line 208 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/214#-L7kflW0-CtiubOTJGvW:-L7kmmTKsd83ME72imA1:bfmjq0r) ([raw file](https://github.com/sillsdev/flexbridge/blob/54fc207e1f024da41ae5a52d9ebe90215ebe5d4c/download_dependencies_linux.sh#L208)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

That concerns me that the .dll.config disappeared from the list, but this .sh file is generated, so hopefully that means we don't need the .dll.config any more.

I see some .mdb files are gone now, too. 

Maybe both have to do with using .NET Standard or Mono 5 or something.
</blockquote></details>

I heard something about .mdb files not being relevant anymore, I would have expected them to be replaced by .pdb files, but I guess not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/214)*

**Pull request merged**
