### PR TITLE
build: Move to new CHANGELOG.md format

### LINKED ISSUE #289: [feature/nuget] Adjust changelogs
From [code review comment](https://github.com/sillsdev/flexbridge/pull/251#pullrequestreview-346070187) in #251:

> We have been keeping a changelog for flexbridge for many years in debian/changelog and we have build scripts in this repository that have been used to keep this as well as some public documentation up to date.

The build scripts etc should be changed to take the changes from `CHANGELOG.md` and update `debian/changelog` and the documentation etc.

### PR DESCRIPTION
**Pull request by marksvc**
- Move ReleaseNotes.md into CHANGELOG.md to preserve historic notes.
- Modify the documentation for using CHANGELOG.md.
- Add NuGet package SIL.ReleaseTasks, and import
  SIL.ReleaseTasks.props so tasks like StampChangelogFileWithVersion
  can be found.
- Tabs in ReadMe.md were changed to 4 spaces.

Closes #289

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/299)

### CODE REVIEW

**Comment by marksvc** [comment]
@jasonleenaylor and @papeh , is this what's needed for #289 ?

**Review by ermshiperete — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/299)* status: all files reviewed, 7 unresolved discussions (waiting on @marksvc)

___
*[CHANGELOG.md, line 66 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFxiimEgTh6JZif-7H:-MOFxiimEgTh6JZif-7I:bcc161z) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/CHANGELOG.md#L66)):*
> ```Markdown
> * Support FieldWorks 9
> 
> ## 2.6.2 05-Mar-2018
> ```

Does it matter that we don't have an empty line after the headings? I guess the tools can deal with that (or don't care). The recommended style for MD is to have a empty line before and after a heading, but it doesn't really matter.
___
*[ReadMe.md, line 56 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFyJgU-NheSEfIYd6X:-MOFyJgU-NheSEfIYd6Y:b-crj63f) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L56)):*
> ```Markdown
> 
>     - Edit `GitVersion.yml` if you are making a major or minor version number jump, by modifying the
>     `next-version:` line. The third place digit will be incremented automatically by GitVersion.
> ```

Usually it shouldn't be necessary to edit `GitVersion.yml` if the commit message contains the semver tags (`+semver:major` or `+semver:minor`), only if we skip version numbers for whatever reason, e.g. from 5.6 to 7.
___
*[ReadMe.md, line 61 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFytMX5wX_a_9v6jSh:-MOFytMYDnhy_Q3ig9o3:b-ddxy2) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L61)):*
> ```Markdown
> 
>     - Edit `CHANGELOG.md` by editing or adding to the items in the `## [Unreleased]` section. This will be published
> 	  as release notes for users.
> ```

nit: indentation with tab whereas in other places you changed it to space. Same in the next paragraph.
___
*[ReadMe.md, line 80 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFzHJh3dJGcRBjkDJx:-MOFzHJh3dJGcRBjkDJy:b-hfdumv) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L80)):*
> ```
> For major or minor version bumps 
> ```

Tagging should happen after each release, not just major and minor version bumps.
___
*[ReadMe.md, line 86 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFznHn-dhZ1JraKmpv:-MOFznHn-dhZ1JraKmpw:b-qqx7rh) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L86)):*
> ```Markdown
> 
>     - The Windows version is released through two jobs on TeamCity: "Installer" and "Patcher". The first three
> 	  version numbers come from the `version` file; the fourth-place version number is always 1 for "Installer"
> ```

nit: indentation with tab (same next three lines)
___
*[build/FLExBridge.proj, line 17 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOG-fll6RC6CJyHoKRc:-MOG-fll6RC6CJyHoKRd:bnm8u5r) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/build/FLExBridge.proj#L17)):*
> ```XML
> 		<ExtraExcludeCategories Condition="'$(teamcity_version)' != ''">SkipOnTeamCity,$(ExtraExcludeCategories)</ExtraExcludeCategories>
> 		<Release Condition="'$(Release)' == ''">true</Release>
> 		<RestartBuild Condition="!Exists('$(RootDir)/packages/GitVersionTask/build/GitVersionTask.dll') Or !Exists('$(RootDir)/packages/SIL.BuildTasks/tools/SIL.BuildTasks.dll') Or !Exists('$(RootDir)/packages/NUnit.ConsoleRunner/tools/nunit3-console.exe')">true</RestartBuild>
> ```

You should add a check for `SIL.ReleaseTasks.dll`.
___
*[build/FLExBridge.proj, line 64 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOG-Apd6xCgHTpxOuEj:-MOG-Ape-pO6pIHHrHT4:bu6klox) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/build/FLExBridge.proj#L64)):*
> ```XML
> 		<Exec Command='$(NuGetCommand) install GitVersionTask -excludeVersion -version 5.3.4 -solutionDirectory "$(RootDir)"' />
> 		<Exec Command='$(NuGetCommand) install SIL.BuildTasks -excludeVersion -version 2.3.4 -solutionDirectory "$(RootDir)"' />
> 		<Exec Command='$(NuGetCommand) install SIL.ReleaseTasks -excludeVersion -version 2.3.4 -solutionDirectory "$(RootDir)"' />
> ```

I guess this needs to be incremented once the changes in the SIL.BuildTasks repo are merged and a new nuget package available.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/299)* status: all files reviewed, 6 unresolved discussions (waiting on @ermshiperete and @marksvc)

___
*[CHANGELOG.md, line 66 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFxiimEgTh6JZif-7H:-MOHn1lD0BL-3l69SYMc:b-pqzcmr) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/CHANGELOG.md#L66)):*
No it doesn't matter for the tools. They can handle the input either way. 

> recommended style

I just had a look at https://spec.commonmark.org/0.29/#atx-headings and  https://github.github.com/gfm/#atx-headings , and it looks like it's at least okay to not have a blank line in between. But I I'll insert newlines around all the following version body descriptions if you prefer?
___
*[ReadMe.md, line 56 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFyJgU-NheSEfIYd6X:-MOHoVbEAyn90pVatab6:bss4a2b) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L56)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Usually it shouldn't be necessary to edit `GitVersion.yml` if the commit message contains the semver tags (`+semver:major` or `+semver:minor`), only if we skip version numbers for whatever reason, e.g. from 5.6 to 7.
</blockquote></details>

Removed.
___
*[ReadMe.md, line 61 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFytMX5wX_a_9v6jSh:-MOHodQE8Gkh-ZxYlP7s:b-10zg8a) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L61)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

nit: indentation with tab whereas in other places you changed it to space. Same in the next paragraph.
</blockquote></details>

Thank you. 
___
*[ReadMe.md, line 80 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOFzHJh3dJGcRBjkDJx:-MOHooEgBoFwMSKO_bWy:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/ReadMe.md#L80)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

> ```
> For major or minor version bumps 
> ```

Tagging should happen after each release, not just major and minor version bumps.
</blockquote></details>

Done.
___
*[build/FLExBridge.proj, line 17 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOG-fll6RC6CJyHoKRc:-MOHpGQg5SMZPSX7k_wN:bxqjlik) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/build/FLExBridge.proj#L17)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

You should add a check for `SIL.ReleaseTasks.dll`.
</blockquote></details>

Done. I have found "RestartBuild" to be a confusing label. Is what is meant here "Whether or not we should do a full build from the beginning"? Maybe it should be called `FullBuildRequired` or something.

Also, would a good way to refactor this be something like the following so we don't need to basically duplicate all the paths, or is the way it's written now important/significant/right/preferable ?

<RestartBuild>true</RestartBuild>
<RestartBuild Condition="Exists('$(RootDir)/packages/GitVersionTask/build/GitVersionTask.dll') 
    And Exists('$(RootDir)/packages/SIL.BuildTasks/tools/SIL.BuildTasks.dll') 
    And Exists('$(RootDir)/packages/SIL.ReleaseTasks/tools/net461/SIL.ReleaseTasks.dll') 
    And Exists('$(RootDir)/packages/NUnit.ConsoleRunner/tools/nunit3-console.exe')"
    >false</RestartBuild>
___
*[build/FLExBridge.proj, line 64 at r1](https://reviewable.io/reviews/sillsdev/flexbridge/299#-MOG-Apd6xCgHTpxOuEj:-MOHqWKE5zosMFFeF0Sr:b-79wj66) ([raw file](https://github.com/sillsdev/flexbridge/blob/39322e815a875c14b4e815315acaa41271827145/build/FLExBridge.proj#L64)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I guess this needs to be incremented once the changes in the SIL.BuildTasks repo are merged and a new nuget package available.
</blockquote></details>

Yes and that occurred to me after work, so I'm glad we haven't submitted this PR yet then :)

**Review by ermshiperete — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/299)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Review by ermshiperete — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/299#-:-MUIAV6TA7aFFl2CQJ1R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Pull request merged**
