### PR TITLE
Create new bridge for LfMerge (v3)

### PR DESCRIPTION
**Pull request by ermshiperete**
This bridge is UI independent and currently supports only send/receive.

This PR supersedes #89.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/92)

### CODE REVIEW

**Comment by regnrand** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 26 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJIRUqUaJGC75mvcW0:-KGJIRUqUaJGC75mvcW1:-903899608) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L26)):*
The new V1.1 doc says LF project creators will be asked if they want it S/R enabled. If the user says 'yes', then the next step is to find out what LD projects the user can connect to. Once a suitable LD project is selected, then a clone is made of it on the LF server. That tells me we already have at least two FB 'actions' for v1.1. So, we may as well drop this method and go a single method and have LFBridge select the correct LF action handler out of all handlers it can find.

As far as parameters for the method goes.... It could be like this:

string actionType // Added to the orginal enum, but unique to LF Bridge action needs to not be ambiguous with other action types inthe enum
IProgress progress
Dictionary<string, string> options

Isn't clear to me if the provided IProgress is the logger you used to have, the one that is fed to Chorus, or if it works for both cases.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 48 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJQid2s_pEvDulTwK8:-KGJQid2s_pEvDulTwK9:42576755) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L48)):*
This needs to be the full pathname, or it must be in the same folder as LFBridge.

---

*[src/TriboroughBridge-ChorusPlugin/Utilities.cs, line 95 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KFoxn2IMPDSN1xFB7zd:-KFoxn2IMPDSN1xFB7ze:-1822419014) ([raw file](https://github.com/sillsdev/flexbridge/blob/22da247a6348605a447549204b86d5d5bd083c5f/src/TriboroughBridge-ChorusPlugin/Utilities.cs#L95)):*
Just get rid of it, since there can be no code using it outside of FB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by ermshiperete** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 26 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJIRUqUaJGC75mvcW0:-KGMeZDdhfdYc_qMOTuv:-344185801) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L26)):*
I realized that ILogger and the IProgress were implemented by the same object, so I decided that it is sufficient to pass it only once and use the existing IProgress interface.

I don't see what benefits we would gain by having a single public method. That _single method_ has to select the appropriate action based on the actionType and convert the passed-in options to the required parameters for the action. Seems to me having _multiple methods_, one for each action, that directly take the required parameters would be easier, and would allow the compiler to verify that all required parameters are passed.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 48 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJQid2s_pEvDulTwK8:-KGMgCto6GtvSORXcVJZ:2056810270) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L48)):*
yes, that will be in the same folder.

---

*[src/TriboroughBridge-ChorusPlugin/Utilities.cs, line 95 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KFoxn2IMPDSN1xFB7zd:-KGMhOF3Wc8-AKGUqFU4:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/22da247a6348605a447549204b86d5d5bd083c5f/src/TriboroughBridge-ChorusPlugin/Utilities.cs#L95)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by regnrand** [comment]
Review status: 0 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 26 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJIRUqUaJGC75mvcW0:-KGNJM3YoU8hupmqEkh0:-728321801) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L26)):*
Chorus will need an IProgess instance. This one can be passed on to Chorus, but then you can count on it containing a "lot" of stuff not related to the main syslog work. Or, this one can be reserved for that syslog work, and a new UI-less one created for Chorus' use. The down side of that new one is that LF Merge won't know what it contained.

The benefit of a single method is that it follows the desired 'uniform interface' concept in FB. That then, lets the client and FB develop more independently (read: you will no longer need to first add a new method to FB and then get LFMerge to compile using it with dependent PRs blocking things).

Say you added a new FB type action to LfMerge, but had not yet added support for it in FB (say its PR approval was held up for some reason). LfMerge would then get the functional equivalent of a website's "Page Not Found, 404" response from FB, not a failure to compile problem.

Verification of the parameters, relative to a given action, has to happen no matter what. It is no easier or harder to do in a one method world than in a multiple method world.

At the end of the day, I doubt I will outright reject having multiple methods, but it will be a new code 'smell' in FB.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 48 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJQid2s_pEvDulTwK8:-KGNQB2ZLHydLQ3oFZw-:-702274517) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L48)):*
'Will be' and 'really is' are not quite the same. You will be safer to make sure it exists. It's just part of that parameter checking mentality in FB.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 28 \[r4\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNNr1AM_M6_pCGraRc:-KGNNr1BykYWZcxIJsn4:-995464878) ([raw file](https://github.com/sillsdev/flexbridge/blob/c1988c317d679f10e7b7a04eed50e668c7d600f9/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L28)):*
This feels like a pizza I ate a day or two ago that won't seem to digest like it should.

Can there be a new interface and then have LFMerge and main FB each have an impl of it that gets imported. Then the main "CheckRepositoryBranches" method can pass on the work to delegate interface impl. That new interface would have one method with the same parameters as the main method.

In principle, I don't really object, other than the rest of FB does this sort of thing via those delegates, so there should be some good reason to add new stuff like this Action. I don't yet see the reason for adding it.

---

*[src/TriboroughBridge-ChorusPlugin/Utilities.cs, line 95 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KFoxn2IMPDSN1xFB7zd:-KGNPAC9L-ufvmOicVs1:677105359) ([raw file](https://github.com/sillsdev/flexbridge/blob/22da247a6348605a447549204b86d5d5bd083c5f/src/TriboroughBridge-ChorusPlugin/Utilities.cs#L95)):*
Thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by ermshiperete** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 48 \[r3\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGJQid2s_pEvDulTwK8:-KGNaL77UJo81cPmnJTw:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/f70bb7be3b0982be173738e89e1b50690125f6e8/src/LfMergeBridge/LfMergeBridge.cs#L48)):*
Done.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 28 \[r4\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNNr1AM_M6_pCGraRc:-KGNkvJEzFXD6DAOUi4g:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/c1988c317d679f10e7b7a04eed50e668c7d600f9/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L28)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by regnrand** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, line 32 \[r5\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNsDmrDwvWwh4HFYwC:-KGNsDmrDwvWwh4HFYwD:-1921464506) ([raw file](https://github.com/sillsdev/flexbridge/blob/b0b9a2cb85dce89baa6fa3894870db63b5b83547/src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs#L32)):*
I think this class now has too many responsibilities. Can a new class be made for the ICheckRepositoryBranches impl?

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 18 \[r5\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNsdG4gDxr8RFkciue:-KGNsdG5lwTcRImujN39:-1810034127) ([raw file](https://github.com/sillsdev/flexbridge/blob/b0b9a2cb85dce89baa6fa3894870db63b5b83547/src/LfMergeBridge/LfMergeBridge.cs#L18)):*
I think this class now has too many responsibilities. And, it looks like it is now instantiated. Was it not static before? Can a new class be made for the ICheckRepositoryBranches impl?

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 28 \[r4\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNNr1AM_M6_pCGraRc:-KGNyF3uXOfIBsSF5ilG:-831847884) ([raw file](https://github.com/sillsdev/flexbridge/blob/c1988c317d679f10e7b7a04eed50e668c7d600f9/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L28)):*
How does it know which implementation to import on a dev machine?

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 19 \[r5\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNvnZBv49BGUNP_Q22:-KGNvnZBv49BGUNP_Q23:1872575229) ([raw file](https://github.com/sillsdev/flexbridge/blob/b0b9a2cb85dce89baa6fa3894870db63b5b83547/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L19)):*
Does it work to import the ICheckRepositoryBranches interface, when the main class isn't exported by MEF?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by ermshiperete** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, line 32 \[r5\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNsDmrDwvWwh4HFYwC:-KGRGtrjziz3_1HiPX-U:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/b0b9a2cb85dce89baa6fa3894870db63b5b83547/src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs#L32)):*
Done.

---

*[src/LfMergeBridge/LfMergeBridge.cs, line 18 \[r5\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNsdG4gDxr8RFkciue:-KGRGvOif91u4AgN3SEh:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/b0b9a2cb85dce89baa6fa3894870db63b5b83547/src/LfMergeBridge/LfMergeBridge.cs#L18)):*
Done.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 28 \[r4\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNNr1AM_M6_pCGraRc:-KGOE31Kx5OK0z7DO1sx:-654578944) ([raw file](https://github.com/sillsdev/flexbridge/blob/c1988c317d679f10e7b7a04eed50e668c7d600f9/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L28)):*
FB imports all `*-ChorusPlugin.dll` and so uses the one from `FLEx-ChorusPlugin`. 

LfMergeBridge imports `Lib*-ChorusPlugin.dll` (and so won't see `FLEx-ChorusPlugin`) but also imports `LfMergeBridge.dll` and so will use the other implementation.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 19 \[r5\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNvnZBv49BGUNP_Q22:-KGRNajBFHBWvuDBkFlu:-764998648) ([raw file](https://github.com/sillsdev/flexbridge/blob/b0b9a2cb85dce89baa6fa3894870db63b5b83547/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L19)):*
Good point. No, it doesn't work. I guess that's why I initially passed the func as parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by regnrand** [comment]
Review status: 0 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/FLEx-ChorusPlugin/Infrastructure/CheckRepositoryBranches.cs, line 16 \[r8\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGSuloUJt7ibDT-o0dz:-KGSuloVXadoK_SVr-4U:-1670841731) ([raw file](https://github.com/sillsdev/flexbridge/blob/62b765cc360f0ee1b7885c263e4fd5305d5b9663/src/FLEx-ChorusPlugin/Infrastructure/CheckRepositoryBranches.cs#L16)):*
Should not be public and probably should be sealed.

---

*[src/LfMergeBridge/CheckRepositoryBranchesNoOp.cs, line 13 \[r8\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGSuxlcEsOtGyPmCgGF:-KGSuxlcEsOtGyPmCgGG:-1670841731) ([raw file](https://github.com/sillsdev/flexbridge/blob/62b765cc360f0ee1b7885c263e4fd5305d5b9663/src/LfMergeBridge/CheckRepositoryBranchesNoOp.cs#L13)):*
Should not be public and probably should be sealed.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs, line 28 \[r4\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGNNr1AM_M6_pCGraRc:-KGSsVUUM9ztn1YbOXlp:1155968382) ([raw file](https://github.com/sillsdev/flexbridge/blob/c1988c317d679f10e7b7a04eed50e668c7d600f9/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSychronizerAdjunct.cs#L28)):*
Nice. Thx.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/ICheckRepositoryBranches.cs, line 10 \[r8\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGSvFR9ubpVuBtrg5Bm:-KGSvFR9ubpVuBtrg5Bn:939738354) ([raw file](https://github.com/sillsdev/flexbridge/blob/62b765cc360f0ee1b7885c263e4fd5305d5b9663/src/LibFLExBridge-ChorusPlugin/Infrastructure/ICheckRepositoryBranches.cs#L10)):*
Should be internal, not public.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by ermshiperete** [comment]
Review status: 0 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/FLEx-ChorusPlugin/Infrastructure/CheckRepositoryBranches.cs, line 16 \[r8\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGSuloUJt7ibDT-o0dz:-KGVoCCt3_GnYCkHfaRP:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/62b765cc360f0ee1b7885c263e4fd5305d5b9663/src/FLEx-ChorusPlugin/Infrastructure/CheckRepositoryBranches.cs#L16)):*
Done.

---

*[src/LfMergeBridge/CheckRepositoryBranchesNoOp.cs, line 13 \[r8\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGSuxlcEsOtGyPmCgGF:-KGVoHkpHJr8ZW2twL3h:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/62b765cc360f0ee1b7885c263e4fd5305d5b9663/src/LfMergeBridge/CheckRepositoryBranchesNoOp.cs#L13)):*
Done.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/ICheckRepositoryBranches.cs, line 10 \[r8\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/92#-KGSvFR9ubpVuBtrg5Bm:-KGVob9Op8POn5XbTKW3:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/62b765cc360f0ee1b7885c263e4fd5305d5b9663/src/LibFLExBridge-ChorusPlugin/Infrastructure/ICheckRepositoryBranches.cs#L10)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by megahirt** [comment]
Reviewed 29 of 29 files at r1, 10 of 10 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 5 of 5 files at r5, 14 of 15 files at r6, 4 of 4 files at r7, 13 of 13 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/92)*

**Comment by megahirt** [comment]
Randy, I'll merge this PR per our discussion earlier today and since Eberhard has fixed the things you asked for.

**Pull request merged**
