### PR TITLE
Internalize API & Improve LF Bridge action handlers

### PR DESCRIPTION
**Pull request by regnrand**
Includes:
1. Improve action handlers for LF Bridge
2. Make nearly all interface implementations explicit.
3. Move some files around.
4. Broke up some multi-class files into single class files
5. Renamed some constants & utilities files.
6. Refactor UpdateBranchHelper to be static and use
	new IUpdateBranchHelperStrategy interface.
7. Update copyright dates.
8. Run FwDataNester app on my 45 test projects:
	A. split, rejoin, compare original with rejoined.
	B. validate split files.
	C. check for ambiguous elements.

Signed-off-by: Randy Regnier <rbregnier@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/100)

### CODE REVIEW

**Comment by irahopkinson** [comment]
Reviewed 13 of 260 files at r1.
Review status: 13 of 251 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100)*

**Comment by rmunn** [comment]
Review status: 13 of 251 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 52 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgObZgeVYYWgfltf8L:-KIgObZgeVYYWgfltf8M:-1897610450) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L52)):*
> ```Smalltalk
> 			Require.That(options.ContainsKey(LfMergeBridgeUtilities.FullPathToProjectKey), @"Missing required 'fullPathToProject' key in 'options'.");
> 			Require.That(options.ContainsKey(LfMergeBridgeUtilities.FwdataFilenameKey), @"Missing required 'fwdataFilename' key in 'options'.");
> 			Require.That(options.ContainsKey(LfMergeBridgeUtilities.FdoDataModelVersionKey), @"Missing required 'fdoDataModelVersionKey' key in 'options'.");
> ```

That error message should probably be "Missing required 'fdoDataModelVersion' key in 'options'." (I.e., without the word "Key" in the key name).

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 52 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgOtr88N4tQceaTOpi:-KIgOtr9RO0Jej1kZygu:-485628008) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L52)):*
> ```Smalltalk
> 			Require.That(options.ContainsKey(LfMergeBridgeUtilities.FullPathToProjectKey), @"Missing required 'fullPathToProject' key in 'options'.");
> 			Require.That(options.ContainsKey(LfMergeBridgeUtilities.FwdataFilenameKey), @"Missing required 'fwdataFilename' key in 'options'.");
> 			Require.That(options.ContainsKey(LfMergeBridgeUtilities.FdoDataModelVersionKey), @"Missing required 'fdoDataModelVersionKey' key in 'options'.");
> ```

This code should also check for the presence of the fixFwDataExePath key, if that change on line 108 was intended. (See my comment on line 108 for more details).

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgPW9Di3Y2SPKepoI0:-KIgPW9Di3Y2SPKepoI1:-245654236) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L108)):*
> ```Smalltalk
> 
> 			// Set up adjunct.
> 			var syncAdjunct = new FlexBridgeSychronizerAdjunct(Path.Combine(fullPathToProject, options[LfMergeBridgeUtilities.FwdataFilenameKey]), options[FwDataExe], false, false);
> ```

It looks like `options[FwDataExe]` is a mistake. If you intended the options dictionary to include the filename and/or path of the FixFwData.exe program to execute, that should probably be `options[LfMergeBridgeUtilities.FixFwDataExePathKey]` instead (setting that to some appropriate string, of course), and the `Require.That` calls at the start of the function should check for its presence. As it stands now, we're checking for an undocumented "FixFwData.exe" key in the options dictionary, and if that key is not present, LfMergeBridge fails with an uninformative `System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.`

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgTSwMvpeO-l7RDVkD:-KIgTSwMvpeO-l7RDVkE:-1181810610) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L108)):*
> ```Smalltalk
> 
> 			// Set up adjunct.
> 			var syncAdjunct = new FlexBridgeSychronizerAdjunct(Path.Combine(fullPathToProject, options[LfMergeBridgeUtilities.FwdataFilenameKey]), options[FwDataExe], false, false);
> ```

BTW, I can't say that I've reviewed this entire class yet. I need to spend some time reading the FlexBridge code, to understand what it's supposed to do, before I can say that I understand the implications of these changes. I'm commenting on the one thing that I know needs a fix, but I will probably have other comments later on as I read more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100)*

**Comment by regnrand** [comment]
Review status: 13 of 251 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 52 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgObZgeVYYWgfltf8L:-KIh5yZXcjT5RhCcNv6O:1280941626) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L52)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> That error message should probably be "Missing required 'fdoDataModelVersion' key in 'options'." (I.e., without the word "Key" in the key name).
</details>
Done. I also changed the names of the constants to match the key string.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 52 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgOtr88N4tQceaTOpi:-KIh7Ix7BhY8s0lybLjx:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L52)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> This code should also check for the presence of the fixFwDataExePath key, if that change on line 108 was intended. (See my comment on line 108 for more details).
</details>
Done.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgPW9Di3Y2SPKepoI0:-KIh6wWjPeBveTgy-6tm:-586760544) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L108)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> It looks like `options[FwDataExe]` is a mistake. If you intended the options dictionary to include the filename and/or path of the FixFwData.exe program to execute, that should probably be `options[LfMergeBridgeUtilities.FixFwDataExePathKey]` instead (setting that to some appropriate string, of course), and the `Require.That` calls at the start of the function should check for its presence. As it stands now, we're checking for an undocumented "FixFwData.exe" key in the options dictionary, and if that key is not present, LfMergeBridge fails with an uninformative `System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.`
</details>
Good catch. I changed it to the local variable 'fwDataExePathname', which is set around line 56.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIgTSwMvpeO-l7RDVkD:-KIh7Lm2bckNhdPqVgFl:2105314763) ([raw file](https://github.com/sillsdev/flexbridge/blob/ab07d400cb9982c6a0b0bc2fac826e8be7b9caff/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L108)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> BTW, I can't say that I've reviewed this entire class yet. I need to spend some time reading the FlexBridge code, to understand what it's supposed to do, before I can say that I understand the implications of these changes. I'm commenting on the one thing that I know needs a fix, but I will probably have other comments later on as I read more.
</details>
So long as we all understand that 'later' means 'no later than my Friday evening', when I merge this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100)*

**Comment by rmunn** [comment]
In general, this looks good. I have a couple of comments on the `LanguageForgeMakeCloneActionHandler.cs` file, but apart from those two comments, I'm OK with merging in this PR.

<details><summary><i>Previously, regnrand (Randy Regnier) wrote…</i></summary>
> #### Internalize API &amp; Improve LF Bridge action handlers
> 
> Includes:
> 
> 1. Improve action handlers for LF Bridge
> 
> 2. Make nearly all interface implementations explicit.
> 
> 3. Move some files around.
> 
> 4. Broke up some multi-class files into single class files
> 
> 5. Renamed some constants & utilities files.
> 
> 6. Refactor UpdateBranchHelper to be static and use
> 
> 	new IUpdateBranchHelperStrategy interface.
> 
> 7. Update copyright dates.
> 
> 8. Run FwDataNester app on my 45 test projects:
> 
> 	A. split, rejoin, compare original with rejoined.
> 
> 	B. validate split files.
> 
> 	C. check for ambiguous elements.
> 
> 
> 
> Signed-off-by: Randy Regnier <rbregnier@gmail.com>
> 
> 
> 
</details>


---

Reviewed 256 of 260 files at r1, 3 of 4 files at r2.
Review status: 250 of 251 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs, line 100 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIlMEbZ4Z1gl6XvQ17P:-KIlMEbZ4Z1gl6XvQ17Q:534511696) ([raw file](https://github.com/sillsdev/flexbridge/blob/6f5f2ce694d3dd5cfed192f26ae44cbcfddd13dd/src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs#L100)):*
> ```Smalltalk
> 
> 			// Did get the clone.
> 			if (expectedFullPathToProjectCloneFolder != actualClonePath)
> ```

After talking this over with Ira, I believe this if statement is unnecessary. We can handle the folder name being different from what we expected, so there's no need to treat this scenario as an error. Instead, just add the `actualClonePath` to the output being sent to LanguageForge (line 125). Then we'll be able to know where the clone ended up, and store the appropriate path in the LanguageForge database.

---

*[src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs, line 125 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIlNbSfRsoNjaojJsuq:-KIlNbSfRsoNjaojJsur:-342171262) ([raw file](https://github.com/sillsdev/flexbridge/blob/6f5f2ce694d3dd5cfed192f26ae44cbcfddd13dd/src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs#L125)):*
> ```Smalltalk
> 
> 			// Notify LF.
> 			LfMergeBridgeUtilities.AppendLineToSomethingForClient(ref somethingForClient, string.Format("{0} {1}: new clone created on branch '{2}'", cloneBase, LfMergeBridgeUtilities.success, workingSetRevision.Branch));
> ```

As mentioned in my line-100 comment, it would be nice if this could be:

    LfMergeBridgeUtilities.AppendLineToSomethingForClient(ref somethingForClient, string.Format("{0} {1}: new clone created on branch '{2}' in folder {3}", cloneBase, LfMergeBridgeUtilities.success, workingSetRevision.Branch, actualClonePath));

If the actual clone path is not the folder that we were expecting, that won't cause us a serious issue -- as long as LfMergeBridge reports that fact to us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-:-KIlQAOG2I92529k-ohc:1050776669)*

**Comment by rmunn** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100)*

**Comment by regnrand** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs, line 100 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIlMEbZ4Z1gl6XvQ17P:-KImTft_86xDEe6jzbMa:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6f5f2ce694d3dd5cfed192f26ae44cbcfddd13dd/src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs#L100)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> After talking this over with Ira, I believe this if statement is unnecessary. We can handle the folder name being different from what we expected, so there's no need to treat this scenario as an error. Instead, just add the `actualClonePath` to the output being sent to LanguageForge (line 125). Then we'll be able to know where the clone ended up, and store the appropriate path in the LanguageForge database.
</details>
Done.

---

*[src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs, line 125 \[r2\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-KIlNbSfRsoNjaojJsuq:-KImURTIoVhN9nxCvsZC:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/6f5f2ce694d3dd5cfed192f26ae44cbcfddd13dd/src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs#L125)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> As mentioned in my line-100 comment, it would be nice if this could be:
> 
>     LfMergeBridgeUtilities.AppendLineToSomethingForClient(ref somethingForClient, string.Format("{0} {1}: new clone created on branch '{2}' in folder {3}", cloneBase, LfMergeBridgeUtilities.success, workingSetRevision.Branch, actualClonePath));
> 
> If the actual clone path is not the folder that we were expecting, that won't cause us a serious issue -- as long as LfMergeBridge reports that fact to us.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100)*

**Comment by rmunn** [comment]
OK, looks good now. I'd say this is ready to merge.

<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> In general, this looks good. I have a couple of comments on the `LanguageForgeMakeCloneActionHandler.cs` file, but apart from those two comments, I'm OK with merging in this PR.
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/100#-:-KInEJ3agjJux1GvDjgI:1806468917)*

**Pull request merged**
