### PR TITLE
Fix linux build and documentation

### PR DESCRIPTION
**Pull request by irahopkinson**
I've updated the **README.md** based on what I learnt to get it to build in Linux.

I've updated **NDesk.DBus.dll** from my FW *lfmerge* branch build. I looked at adding this as a dependency but that looked too hard (I don't have or know anything about Ruby) and an older version of the DLL was already in the repo so I have just updated it.

**environ** now knows where *Mercurial* is for development.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/88)

### CODE REVIEW

**Comment by ermshiperete** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[environ, line 1 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/88#-KCyFlwA_t5A0K9w0ZAP:-KCyFlwBhv5trPVYjdRk:-1811084900) ([raw file](https://github.com/sillsdev/flexbridge/blob/5e97408543156e8434b7427843ad9943e57cc7d2/environ#L1)):*
This is not necessary since this file is intended to be sourced, not run as a shell script. But it doesn't hurt.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/88#-:-KCyIHT9W-Sh7fkNN4xr:980077423)*

**Comment by irahopkinson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[environ, line 1 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/88#-KCyFlwA_t5A0K9w0ZAP:-KD1Zt8EBXPHFQOTe8Uy:-1274810132) ([raw file](https://github.com/sillsdev/flexbridge/blob/5e97408543156e8434b7427843ad9943e57cc7d2/environ#L1)):*
I had thought this was the change that fixed the error I was getting with FW saying that it couldn't find Mecurial. I've tested with the environ change reverted and its all good so I have pushed the reverted environ file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/88)*

**Comment by ermshiperete** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/88)*

**Comment by irahopkinson** [comment]
Hi Eberhard, who does the merge? Blessings, Ira

On Fri, Mar 18, 2016 at 3:53 PM, Eberhard Beilharz <notifications@github.com
> wrote:

> Reviewed 1 of 1 files at r2.
> Review status: all files reviewed at latest revision, all discussions
> resolved.
> ------------------------------
>
> *Comments from the review on Reviewable.io
> <https://reviewable.io:443/reviews/sillsdev/flexbridge/88>*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/flexbridge/pull/88#issuecomment-198262049>
>



-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>

**Pull request merged**
