### PR TITLE
Recent fixes and change to geckofx45

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/198)

### CODE REVIEW

**Comment by papeh** [comment]
did you mean to target `develop`? This targets `master`

---

Reviewed 8 of 12 files at r1.
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/198#-L4mMTJpZjJfrgPVcOFX:-L4mMTJqeE_9JTrl_USP:b-88uy2z) ([raw file](https://github.com/sillsdev/flexbridge/blob/e649263dcbc4d711ed69b6d4568440e319bc2e30/Makefile#L22)):*
> ```Makefile
> 	if test ! -d "/tmp/flexbridge"; then mkdir -p "/tmp/flexbridge"; fi;
> 	export FBCommonAppData
> 	./download_dependencies_linux.sh && . ./environ && cd build && xbuild FLExBridge.build.mono.proj /t:Build /p:RootDir=.. /p:teamcity_dotnet_nunitlauncher_msbuild_task=notthere /p:BUILD_NUMBER=$(BUILD_NUMBER) /p:BUILD_VCS_NUMBER=$(BUILD_VCS_NUMBER) /p:UploadFolder=$(UploadFolder) /p:Configuration=DebugMono
> ```

I think we've updated the FLExBridge.proj not to require all of those properties (ideas for future cleanup)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/198#-:-L4mNHAfck4yQp6hTJuR:bz7n3a0)*

**Comment by marksvc** [comment]
Thank you. In this case I do mean to target master so I can backport the work to flexbridge 2.6.

---

Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/flexbridge/198#-:-L4v4bOVCOkJIYAt8E4Y:blbq83g)*

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 4 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 22 at r1](https://beta.reviewable.io/reviews/sillsdev/flexbridge/198#-L4mMTJpZjJfrgPVcOFX:-L4wFec66nEIyMqKYUzu:bltkp5r) ([raw file](https://github.com/sillsdev/flexbridge/blob/e649263dcbc4d711ed69b6d4568440e319bc2e30/Makefile#L22)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I think we've updated the FLExBridge.proj not to require all of those properties (ideas for future cleanup)
</blockquote></details>

(and we no longer have separate FLExBridge.build.$(OS).proj files)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/flexbridge/198#-:-L4wH9QfCVYyMuaFkNLi:bnfp4nl)*

**Comment by marksvc** [comment]
Not submitting yet while a bug, possibly introduced from this code, is investigated elsewhere.

**Pull request merged**
