### PR TITLE
LT-18673 Click on S/R menus leads to crash pt2

### PR DESCRIPTION
**Pull request by gtryus**
This reverts commit 932c63788be9da740bdfc4455b689902512d6487. (#164)
From commit 9b3592323513a588aed008594a650415677e7e20
- Add Flex-ChorusPlugin
- Add Flex-ChorusPluginTests
Update installer to include Flex-ChorusPlugin
Update Readme.md to inform developers not to add Windows.Forms
dependency to LibFlexBridge-ChorusPlugin

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/165)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[FLExBridge.sln, line 15 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEHQLbfRVTNxsm47t3:-KvEHQLbfRVTNxsm47t4:b-ypjt0c) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/FLExBridge.sln#L15)):*
> ```
> 		src\Installer\Installer.wixproj = src\Installer\Installer.wixproj
> 		src\Installer\Installer.wxs = src\Installer\Installer.wxs
> 		ReadMe.md = ReadMe.md
> ```

Are the pic and the ReadMe really necessary in the solution file?

---

*[ReadMe.md, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEI2ARucmNBPtObfn5:-KvEI2ARucmNBPtObfn6:b9owkoy) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L7)):*
> So that part of your chart is off

since this has been corrected in the chart, the comment can be removed here.

---

*[ReadMe.md, line 9 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEIWvChDoGsDEcomRU:-KvEIWvChDoGsDEcomRV:b-rr5kdm) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L9)):*
> There could also be

I don't think this discussion needs to be in the ReadMe.

---

*[ReadMe.md, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEIOKcQnqitaIM_QJE:-KvEIOKcQnqitaIM_QJF:b-ed5v2e) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L10)):*
> ```Markdown
> 
> It is an unfortunate artifact of development history that Flex uses the exe called FlexBridge for S/R for its own data set and for Lift. There really should be a second one Flex calls called LiftBridge with the lift related stuff taken out of the FB exe. (There could also be two dll 'bridge' entry points, instead of exes, to bring it all into the main Flex process, now that Flex is moving into the 64 bit world on Windows.)
> WeSay does not use FlexBridge, as the picture suggests. WeSay talks directly to Chorus.
> ```

Add another newline to make this its own paragraph.

---

*[ReadMe.md, line 98 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEWUN3GUDhPRAz0Pgn:-KvEWUN3GUDhPRAz0Pgo:bdmczg8) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L98)):*
> ```Markdown
>     * Click Build.
> 
> ## TriboroughBridge
> ```

this section could be absorbed into the Architecture heading.

---

*[src/FlexBridgeArch_2017-09-29.xon, line 26 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEQeMZjCxqiUEiQOEx:-KvEQeMZjCxqiUEiQOEy:b-1xn3ws) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FlexBridgeArch_2017-09-29.xon#L26)):*
> ```
> j_(4,"FlexBridge",1,-1107,45,3,0,161,15,8193,0,0,"").
> j_(2,"WeSay",1,-1595,-232,3,0,162,5,8193,0,0,"").
> j_(22,"Chorus",1,-1107,-232,3,0,161,15,8193,0,0,"").
> ```

to be pedantic, Chorus isn't part of the FLExBridge repo; however, if it's too much effort to exclude it from the squircle, I won't withhold approval over this.

---

*[src/FlexBridgeArch_2017-09-29.xon, line 52 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEIdy6NyqRPn_SifSn:-KvEIdy6NyqRPn_SifSo:br88ajy) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FlexBridgeArch_2017-09-29.xon#L52)):*
> ```
> q_(2003,"3|29-09 14:44|GreTrihu|17|13|1|0|1|0|c:\\Users\\Trihus\\Desktop\\FlexBridgeArch_2017-09-29").
> q_(2004,"4|29-09 15:00|GreTrihu|18|12|1|0|1|0|C:\\Users\\Trihus\\gitgtryus\\flexbridge\\src\\FlexBridgeArch_2017-09-29").
> q_(2005,"5|29-09 15:00|GreTrihu|18|12|1|0|1|0|c:\\Users\\Trihus\\gitgtryus\\flexbridge\\src\\FlexBridgeArch_2017-09-29").
> ```

No need to have the date in the name of this file.  Also, since it is generated using a lesser-known tool, it would be good to include a comment about this so that future developers can update the diagram as needed (or export an SVG)

---

*[src/FLEx-ChorusPlugin/Properties/AssemblyInfo.cs, line 18 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvERaC0GWIYSMfYf8DA:-KvERaC0GWIYSMfYf8DB:b4bdcqy) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FLEx-ChorusPlugin/Properties/AssemblyInfo.cs#L18)):*
> ```Smalltalk
> [assembly: InternalsVisibleTo("FwdataTestApp")]
> [assembly: InternalsVisibleTo("TheTurtle")]
> [assembly: InternalsVisibleTo("TheTurtleTests")]
> ```

I don't think the Turtle remains.

I'm assuming this is because this file didn't receive attention when the Turtle was removed; now would be a good time to remove these lines.

---

*[src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvETgnqZ2OUifX1spaW:-KvETgnrbn6af_SKUp1_:bjplb9l) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs#L1)):*
> ```Smalltalk
> // --------------------------------------------------------------------------------------------
> ```

This file is unneeded; the only test is identical to one that now lives in LibFLExBridge-ChorusPluginTests/Integration/MergeIntegrationTests.cs

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs, line 21 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEUqsTB8iYxjADTaLy:-KvEUqsUpoYaQguOHN6d:bgncyv2) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs#L21)):*
> ```Smalltalk
> using TriboroughBridge_ChorusPlugin.Properties;
> 
> namespace FLEx_ChorusPlugin.Infrastructure
> ```

file also needs to be moved

---

*[src/LibFLExBridge-ChorusPluginTests/WinFormsTest.cs, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEVJwv0vWO4XrWcuiN:-KvEVJwv0vWO4XrWcuiO:b-gg5z58) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/LibFLExBridge-ChorusPluginTests/WinFormsTest.cs#L22)):*
> ```Smalltalk
> 						where type.Namespace == "System.Windows.Forms"
> 						select type);
> 			Assert.IsEmpty(formsNamespace, "LibFlexBridge-ChorusPlugin should not reference Windows.Forms. See Readme.md");
> ```

it would be good to test this in LibTriboroughBridge, too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165)*

**Comment by papeh** [comment]
@regnrand

**Comment by gtryus** [comment]
Review status: 23 of 30 files reviewed at latest revision, 11 unresolved discussions.

---

*[FLExBridge.sln, line 15 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEHQLbfRVTNxsm47t3:-KvSzbSPifmukf1Hby1X:bb7f2mf) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/FLExBridge.sln#L15)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Are the pic and the ReadMe really necessary in the solution file?
</blockquote></details>

done

---

*[ReadMe.md, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEI2ARucmNBPtObfn5:-KvSzmh-3N2P_xitRs9L:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L7)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

> So that part of your chart is off

since this has been corrected in the chart, the comment can be removed here.
</blockquote></details>

Done.

---

*[ReadMe.md, line 9 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEIWvChDoGsDEcomRU:-KvSzoLhu12UfDcuEyb1:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L9)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

> There could also be

I don't think this discussion needs to be in the ReadMe.
</blockquote></details>

Done.

---

*[ReadMe.md, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEIOKcQnqitaIM_QJE:-KvSzqAGkmw4y_ZGn9hh:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L10)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Add another newline to make this its own paragraph.
</blockquote></details>

Done.

---

*[ReadMe.md, line 98 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEWUN3GUDhPRAz0Pgn:-KvSzu62ilg5WFa2iL6y:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/ReadMe.md#L98)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

this section could be absorbed into the Architecture heading.
</blockquote></details>

Done.

---

*[src/FLEx-ChorusPlugin/Properties/AssemblyInfo.cs, line 18 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvERaC0GWIYSMfYf8DA:-KvT--_yLmTbYbkzIwM2:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FLEx-ChorusPlugin/Properties/AssemblyInfo.cs#L18)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I don't think the Turtle remains.

I'm assuming this is because this file didn't receive attention when the Turtle was removed; now would be a good time to remove these lines.
</blockquote></details>

Done.

---

*[src/LibFLExBridge-ChorusPluginTests/WinFormsTest.cs, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEVJwv0vWO4XrWcuiN:-KvT-5ZSz-HwhpdXma62:b-lgpvlj) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/LibFLExBridge-ChorusPluginTests/WinFormsTest.cs#L22)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

it would be good to test this in LibTriboroughBridge, too
</blockquote></details>

I reworked and retested this code. The previous code wasn't actually working whereas this code has an empty list here and a list with a member if it is put in the FlexBridge_ChrorusPlugin. Since this code depends on LibTriboroughBridge, this code here should test both.

---

*[src/FlexBridgeArch_2017-09-29.xon, line 26 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEQeMZjCxqiUEiQOEx:-KvT-XQr3FsJjsXS1H5b:b-r57qn1) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FlexBridgeArch_2017-09-29.xon#L26)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

to be pedantic, Chorus isn't part of the FLExBridge repo; however, if it's too much effort to exclude it from the squircle, I won't withhold approval over this.
</blockquote></details>

Yes, it is necessary to understand how Chorus fits with this repo since this repo is a type of instance class of Chorus which adds functionality.

---

*[src/FlexBridgeArch_2017-09-29.xon, line 52 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEIdy6NyqRPn_SifSn:-KvT-VhVSygXeaYND7RU:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FlexBridgeArch_2017-09-29.xon#L52)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

No need to have the date in the name of this file.  Also, since it is generated using a lesser-known tool, it would be good to include a comment about this so that future developers can update the diagram as needed (or export an SVG)
</blockquote></details>

Done.

---

*[src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvETgnqZ2OUifX1spaW:-KvT-hD_DM7Np_nyWmqc:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs#L1)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

This file is unneeded; the only test is identical to one that now lives in LibFLExBridge-ChorusPluginTests/Integration/MergeIntegrationTests.cs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165)*

**Comment by regnrand** [comment]
My recommendation is to abandon this approach, and go back to the merge that was done wrong, redo it, and reply relevant changes done since then, but skip other commits that aimed to fix up the bad merge.

---

Review status: 23 of 30 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-:-KvT09IxEaHk_XbxsN1_:bbhrp4s)*

**Comment by gtryus** [comment]
Review status: 23 of 30 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs, line 21 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEUqsTB8iYxjADTaLy:-KvT1OAi4xo3410K_9m1:b-z6of9e) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs#L21)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

file also needs to be moved
</blockquote></details>

This file is not needed. It is in the original project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165)*

**Comment by gtryus** [comment]
Our plan is to just squash all the commits together.

---

Review status: 23 of 30 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-:-KvT1tD-ra1Jd_q42uAe:bc3kl48)*

**Comment by papeh** [comment]
I'll address my remaining comments when I squash.

---

Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/FlexBridgeRepo.odg, line 0 at r2](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvTKiMVrKCjl2Prv4Vq:-KvTKiMVrKCjl2Prv4Vr:bb7m3jc) ([raw file](https://github.com/sillsdev/flexbridge/blob/5cc2249e8f69bd97294f5cb7bf6787f251e2366f/src/FlexBridgeRepo.odg#L0)):*
oops

---

*[src/FlexBridgeRepo.svg, line 11 at r2](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvTLVPd3t-HwmM0bmYr:-KvTLVPd3t-HwmM0bmYs:brbywtz) ([raw file](https://github.com/sillsdev/flexbridge/blob/5cc2249e8f69bd97294f5cb7bf6787f251e2366f/src/FlexBridgeRepo.svg#L11)):*
> ```SVG
>    <rect x="27" y="21" width="27885" height="21547"/>
>   </clipPath>
>  </defs>
> ```

Perhaps whitespace could be reduced.

---

*[src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs, line 21 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvEUqsTB8iYxjADTaLy:-KvTLfGTpYflCOLYGHv3:b-wo0omo) ([raw file](https://github.com/sillsdev/flexbridge/blob/ec9580b7cde2093cbde740ffc496a855eb714c76/src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs#L21)):*
<details><summary><i>Previously, gtryus wrote…</i></summary><blockquote>

This file is not needed. It is in the original project.
</blockquote></details>

Then I shall remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-:-KvTMEsEV1JOIksZqJgy:bii5zux)*

**Comment by papeh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/FlexBridgeRepo.odg, line  at r2](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-KvTKiMVrKCjl2Prv4Vq:-KvTZFQDI7PwrCeHQhkM:bv5rkzq) ([raw file](https://github.com/sillsdev/flexbridge/blob/5cc2249e8f69bd97294f5cb7bf6787f251e2366f/src/FlexBridgeRepo.odg#L)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

oops
</blockquote></details>

maybe this should stay...LibreOffice doesn't import the SVG as nicely as I'd like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/165#-:-KvTZPvWvxG4eCf1dhdl:bnfp4nl)*

**Pull request merged**
