### PR TITLE
Use RepositoryAddress.Create to create repo path

### PR DESCRIPTION
**Pull request by ermshiperete**
When running tests in LfMerge we use a directory rather than a remote URL, so we need to create the proper RepositoryAddress which the Create() method takes care of.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/97)

### CODE REVIEW

**Comment by regnrand** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 90 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/97#-KHef0Zj7xRZn6LqBhj2:-KHef0Zj7xRZn6LqBhj3:525358360) ([raw file](https://github.com/sillsdev/flexbridge/blob/b6a3a03a78f88b03152d787195ce96edfbbf40b7/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L90)):*
> ```Smalltalk
> 			};
> 			syncOptions.RepositorySourcesToTry.Clear(); // Get rid of any default ones, since LF only sends off to the internet (Language Depot).
> 			syncOptions.RepositorySourcesToTry.Add(RepositoryAddress.Create(options[LfMergeBridgeUtilities.LanguageDepotRepoNameKey], options[LfMergeBridgeUtilities.LanguageDepotRepoUriKey], false));
> ```

Add a comment that it uses the generic creation code in order to make testing easier, since the real world usage would only create "HttpRepositoryPath". Then, LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/97)*

**Comment by ermshiperete** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs, line 90 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/97#-KHef0Zj7xRZn6LqBhj2:-KHeh1e6Ui1nmv2HkvLA:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/b6a3a03a78f88b03152d787195ce96edfbbf40b7/src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs#L90)):*
<details><summary><i>Previously, regnrand (Randy Regnier) wrote…</i></summary>
> Add a comment that it uses the generic creation code in order to make testing easier, since the real world usage would only create "HttpRepositoryPath". Then, LGTM.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/97)*

**Comment by regnrand** [comment]
:lgtm:

<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> #### Use RepositoryAddress\.Create to create repo path
> 
> When running tests in LfMerge we use a directory rather than a remote URL, so we need to create the proper RepositoryAddress which the Create() method takes care of.
> 
> 
> 
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/97#-:-KHeij4cfJ0BU_rg7KoV:1417088721)*

**Comment by irahopkinson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/97)*

**Pull request merged**
