### PR TITLE
Put responsibility for xsd location back on FLEx

### PR DESCRIPTION
**Pull request by gmartin7**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/83)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/83)*

**Comment by regnrand** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, line 147 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/83#-K9XnoPcOobUzKHknLwi:-K9XnoPcOobUzKHknLwj:211545085) ([raw file](https://github.com/sillsdev/flexbridge/blob/28452977356e943450da7ecf33734f0ed2c041eb/src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs#L147)):*
Glad to see all of this 'clutter' go into the bit bucket. Thanks.

---

*[src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs, line 38 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/83#-K9Xm_wGkH3vVo8QHLls:-K9Xm_wGkH3vVo8QHLlt:819964811) ([raw file](https://github.com/sillsdev/flexbridge/blob/56391eb8b5da9a7b03c1152ba7706e1c2e916a77/src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs#L38)):*
It seems odd to throw an exception here. The "CanValidate" method calls this "GetXsdPath" method, and the preferred code would simply return false, if it cannot find the schema and thus is not able to validate the settings file. Theory has it that Chorus will first see if the file can be validated and only if it can be validated, will it then call the main "ValidateFile" method. So, I'm not seeing a need for the exception.

FWIW, "GetXsdPath" is a misleading method name (as is the member variable "_xsdPath". It should really be "GetXsdPathname", since it is in fact returning a pathname, not a path.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/83)*

**Comment by gmartin7** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs, line 38 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/83#-K9Xm_wGkH3vVo8QHLls:-K9Y1oLjIvvhG-6njfaV:-499146009) ([raw file](https://github.com/sillsdev/flexbridge/blob/56391eb8b5da9a7b03c1152ba7706e1c2e916a77/src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs#L38)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/83)*

**Comment by regnrand** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs, line 38 \[r1\]](https://reviewable.io:443/reviews/sillsdev/flexbridge/83#-K9Xm_wGkH3vVo8QHLls:-K9Y3UDM0m3q9v7Z4Azi:1716186060) ([raw file](https://github.com/sillsdev/flexbridge/blob/56391eb8b5da9a7b03c1152ba7706e1c2e916a77/src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs#L38)):*
"Much grass".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/83)*

**Comment by regnrand** [comment]
LGTM

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/flexbridge/83#-:-K9Y3fgmHngWmt6NkELi:676834233)*

**Pull request merged**
