### PR TITLE
Fix environ for fw geckofx upgrade

### PR DESCRIPTION
**Pull request by mccarthyrb**
Set environ-xulrunner libraries to link to Geckofx45 which is
installed with Fieldworks. When running in Debug the libraries
are found in Fieldworks Debug output.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/114)

### CODE REVIEW

**Comment by mccarthyrb** [comment]
The installed is working properly, but the debug environment still needs some work. For some reason it is not picking up the correct environment on my system.

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/common/run-app, line 50 at r2](https://reviewable.io:443/reviews/sillsdev/flexbridge/114#-KSbCACcHmeE_6094MpH:-KSbCACdseUQK0KgU-YZ:b-a1u3gn) ([raw file](https://github.com/sillsdev/flexbridge/blob/144ddf5132ac1ffaee68e3b84a3c224e126fc68d/lib/common/run-app#L50)):*
> ```
> 	XULRUNNER=$(dirname "${LIBXUL}")
> fi
> GECKOFX="${XULRUNNER}/.."
> ```

would $(dirname ${XULRUNNER}) work here?  just asking...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/114)*

**Comment by StephenMcConnel** [comment]
Generally :lgtm: although I have one question.  Can be checked in as-is.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/114#-:-KSbCyP_BtJQJSN_Tvty:bboc8zl)*

**Comment by mccarthyrb** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/common/run-app, line 50 at r2](https://reviewable.io:443/reviews/sillsdev/flexbridge/114#-KSbCACcHmeE_6094MpH:-KSbErCLpTgBgb_ramDt:bzfmtjh) ([raw file](https://github.com/sillsdev/flexbridge/blob/144ddf5132ac1ffaee68e3b84a3c224e126fc68d/lib/common/run-app#L50)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary>
> would $(dirname ${XULRUNNER}) work here?  just asking...
</details>
I am pretty sure that only works with files, not paths. I tried it before and it failed. I could use:
GECKOFX=$(echo "$XULRUNNER" | cut -d "/" -f2)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/114)*

**Comment by mccarthyrb** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/common/run-app, line 50 at r2](https://reviewable.io:443/reviews/sillsdev/flexbridge/114#-KSbCACcHmeE_6094MpH:-KSbHTAXrdi1xDjpiFW-:badu31u) ([raw file](https://github.com/sillsdev/flexbridge/blob/144ddf5132ac1ffaee68e3b84a3c224e126fc68d/lib/common/run-app#L50)):*
<details><summary><i>Previously, mccarthyrb (Brent McCarthy) wrote…</i></summary>
> I am pretty sure that only works with files, not paths. I tried it before and it failed. I could use:
> GECKOFX=$(echo "$XULRUNNER" | cut -d "/" -f2)
</details>
Oops, I was thinking about something else .. That would work :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/114)*

**Pull request merged**
