### PR TITLE
Improve message box to display the current LIFT model

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Display the current and required LIFT model version when importing
a LIFT project created in a newer version of FLEx

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/195)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs, line 46 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4bJW7RnS4NcT6mnbGp:-L4bJW7RnS4NcT6mnbGq:b-as3eq) ([raw file](https://github.com/sillsdev/flexbridge/blob/63bbebf41005adc66b7b3e4fbac4397109879583/src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs#L46)):*
> ```Smalltalk
> 		}
> 
> 		private static string GetLiftVersionNumberString(string repo)
> ```

slightly surprised we don't already have this method somewhere already.

---

*[src/TriboroughBridge-ChorusPlugin/Properties/CommonResources.resx, line 170 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4bKFaP9D8L3i8FO0rL:-L4bKFaP9D8L3i8FO0rM:b-re3rzl) ([raw file](https://github.com/sillsdev/flexbridge/blob/63bbebf41005adc66b7b3e4fbac4397109879583/src/TriboroughBridge-ChorusPlugin/Properties/CommonResources.resx#L170)):*
> ```XML
>   </data>
>   <data name="kFlexUpdateRequired" xml:space="preserve">
> 	<value>You will need to update your version of Flex to obtain the requested project, since it is newer.</value>
> ```

now would be a good opportunity to fix the capitalization of FLEx

---

*[src/TriboroughBridge-ChorusPlugin/Properties/CommonResources.resx, line 173 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4bKSgJHPUfgxaxlUnK:-L4bKSgJHPUfgxaxlUnL:b-9ri2ko) ([raw file](https://github.com/sillsdev/flexbridge/blob/63bbebf41005adc66b7b3e4fbac4397109879583/src/TriboroughBridge-ChorusPlugin/Properties/CommonResources.resx#L173)):*
> ```XML
>   </data>
>   <data name="kFlexUpdateToSupportLift" xml:space="preserve">
>     <value>You are importing a lexicon (LIFT) project that requires a newer version of FieldWorks. Your current version of FieldWorks uses LIFT model version {0}, and version {1} is required. Please update your version of FieldWorks.</value>
> ```

How about:

Your version of FLEx supports LIFT model version {0}, but the requested project uses version {1}. You will need to update your version of FLEx to obtain the requested project.

(shorter message, and consistent use of "FLEx"; my exact wording is not required)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-:-L4bMk1H_5hRqMGaGuPV:bnfp4nl)*

**Comment by papeh** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs, line 46 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4bJW7RnS4NcT6mnbGp:-L4bQepdtjWeg2mfq4tf:b-yz153) ([raw file](https://github.com/sillsdev/flexbridge/blob/63bbebf41005adc66b7b3e4fbac4397109879583/src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs#L46)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We do, it is in updatebranchhelperLift, but it is private, and I don't want to include a new dependency on LiftBridge-ChorusPlugin
</blockquote></details>

I don't see a problem with making that method `internal` and handling all the version getting in UpdateBranchHelperLift.

While you're in the area, you can change all the signatures from `type IUBHS.Method` to `public type Method` and get rid of `AsIUpdate`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/195)*

**Comment by RaymondLuong3** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs, line 46 at r1](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4bJW7RnS4NcT6mnbGp:-L4bp7HoMy2hgKYs1Vlr:b-3m790h) ([raw file](https://github.com/sillsdev/flexbridge/blob/63bbebf41005adc66b7b3e4fbac4397109879583/src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs#L46)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I don't see a problem with making that method `internal` and handling all the version getting in UpdateBranchHelperLift.

While you're in the area, you can change all the signatures from `type IUBHS.Method` to `public type Method` and get rid of `AsIUpdate`.
</blockquote></details>

Yes, I mistook the ObtainProjectStrategyLift class to be in a different project. This simplifies things!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/195)*

**Comment by papeh** [comment]
Reviewed 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs, line 17 at r3](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4c0U-0bZ55V9sjZc3o:-L4c0U-0bZ55V9sjZc3p:b1bxgtz) ([raw file](https://github.com/sillsdev/flexbridge/blob/6067a525f251babfd1825ea0ee7a544ff8b44048/src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs#L17)):*
> ```Smalltalk
> 		internal static float GetLiftVersionNumber(string repoLocation)
> 		{
> 			// Return 0.13 if there is no lift file or it has no 'version' attr on the main 'lift' element.
> ```

this comment has been incorrect for some time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/195)*

**Comment by RaymondLuong3** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs, line 17 at r3](https://reviewable.io:443/reviews/sillsdev/flexbridge/195#-L4c0U-0bZ55V9sjZc3o:-L4c36SH41-kbvC4m74U:b-896fix) ([raw file](https://github.com/sillsdev/flexbridge/blob/6067a525f251babfd1825ea0ee7a544ff8b44048/src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs#L17)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

this comment has been incorrect for some time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/195)*

**Comment by papeh** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/flexbridge/195)*

**Pull request merged**
